################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Base
# @description :
#
################################################################################

base:
  variables:
    entity_id: >
      [[[ return !entity || entity.entity_id; ]]]
    entity_picture: >
      [[[ return !entity || entity.attributes.entity_picture; ]]]
    state: >
      [[[ return entity === undefined || entity.state; ]]]
    state_on: >
      [[[ return ['on', 'home', 'playing', 'unlocked'].indexOf(!entity || entity.state) !== -1; ]]]
    timeout: >
      [[[ return entity === undefined || Date.now() - Date.parse(entity.last_changed); ]]]
  aspect_ratio: 1/1
  show_state: true
  show_icon: true
  size: 90%
  tap_action:
    animation_card: |
      [[[
        const animation_speed_ms = 900;
        const animation = `card_bounce ${animation_speed_ms}ms cubic-bezier(0.22, 1, 0.36, 1)`;
        this.shadowRoot.getElementById("card").style.animation = animation;
        window.setTimeout(() => {
          this.shadowRoot.getElementById("card").style.animation = "none";
        }, animation_speed_ms)
      ]]]
    action: toggle
    haptic: medium
  double_tap_action:
    haptic: success
  hold_action:
    action: call-service
    service: browser_mod.toast
    service_data:
      duration: 3000
      message: >
        Double click to open popup menu
    haptic: failure
  styles:
    grid:
      - grid-template-areas: |
          "i  circle"
          "n  n"
          "s  s"
      - grid-template-columns: repeat(2, 1fr)
      - grid-template-rows: auto repeat(2, min-content)
      - gap: 2%
      - align-items: start
    img_cell:
      - justify-content: start
      - align-items: start
    icon:
      - justify-self: start
      - height: auto
      - color: >
          [[[
            if( variables.state == 'playing' || variables.state == 'home' || variables.state == 'Home' || variables.state == 'cool' )
            { 
              return 'var( --paper-item-icon-active-color )';

            } else if( variables.state == 'on' )
            { 
              return 'var( --paper-item-icon-active-color )';

            } else
            {
              return 'rgba( 255, 255, 255, 0.3 )';

            }
          ]]]
    name:
      - justify-self: start
      - line-height: 115%
      - letter-spacing: 0.05vw
    state:
      - justify-self: start
      - line-height: 115%
      - letter-spacing: 0.05vw

    card:
      - border-radius: var(--button-card-border-radius)
      - -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
      - transition: none
      - padding: 10%
      - --mdc-ripple-color: >
          [[[
            return variables.state_on 
              ? 'rgb(0, 0, 0)' 
              : 'rgba(255, 255, 255, 0.3)';
          ]]]
      - color: >
          [[[
            return variables.state_on 
              ? 'rgba(0, 0, 0, 0.6)' 
              : 'rgba(255, 255, 255, 0.3)';
          ]]]
      - background-color: >
          [[[
            return variables.state_on 
            ? 'rgba(255, 255, 255, 0.8)' 
            : 'rgba(115, 115, 115, 0.2)';
          ]]]
  extra_styles: |
    @media screen and (max-width: 992px) {
      #name, #state {
        letter-spacing: 0.12vw;
      }
    }

    @media screen and (max-width: 1200px) {
      #name, #state {
        letter-spacing: 0.05vw;
      }
    }

    @keyframes card_bounce {
      0% {
        transform: scale(1);
      }
      15% {
        transform: scale(0.9);
      }
      25% {
        transform: scale(1);
      }
      30% {
        transform: scale(0.98);
      }
      100% {
        transform: scale(1);
      }
    }

entity_base:
  fill_container: true
  primary_info: "name"
  secondary_info: "state"
  icon_type: "icon"
  collapsible_controls: true

entity_battery:
  primary: "{{ states(entity) }}%"
  secondary: "{{ states(name) }}"
  icon: |+
    {% set battery_level = (states(entity) | int / 10) | round(0) | int * 10 %}
    {% if battery_level == 100 %}
      mdi:battery
    {% elif battery_level > 20 %}
      mdi:battery-{{ battery_level }}
    {% else %}
      mdi:battery-alert-variant-outline
    {% endif %}
  icon_color: |-
    {% set battery_level = states(entity) | int %}
    {% if battery_level > 90 %}
      green
    {% elif battery_level > 60 %}
      light-green
    {% elif battery_level > 50 %}
      lime
    {% elif battery_level > 40 %}
      yellow
    {% elif battery_level > 30 %}
      amber
    {% elif battery_level > 20 %}
      orange
    {% elif battery_level > 10 %}
      deep-orange
    {% else %}
      red
    {% endif %}
