################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Base
# @description :
#
################################################################################

base:
  variables:
    entity_id: >
      [[[ return !entity || entity.entity_id; ]]]
    entity_picture: >
      [[[ return !entity || entity.attributes.entity_picture; ]]]
    state: >
      [[[ return entity === undefined || entity.state; ]]]
    state_on: >
      [[[ return ['on', 'Run', 'home', 'Home', 'playing', 'unlocked'].indexOf(!entity || entity.state) !== -1; ]]]
    timeout: >
      [[[ return entity === undefined || Date.now() - Date.parse(entity.last_changed); ]]]
  aspect_ratio: 1/1
  show_state: true
  show_icon: true
  size: 90%
  tap_action:
    animation_card: |
      [[[
        const animation_speed_ms = 900;
        const animation = `card_bounce ${animation_speed_ms}ms cubic-bezier(0.22, 1, 0.36, 1)`;
        this.shadowRoot.getElementById("card").style.animation = animation;
        window.setTimeout(() => {
          this.shadowRoot.getElementById("card").style.animation = "none";
        }, animation_speed_ms)
      ]]]
    action: toggle
    haptic: medium
  double_tap_action:
    haptic: success
  hold_action:
    action: call-service
    service: browser_mod.toast
    service_data:
      duration: 3000
      message: >
        Double click to open popup menu
    haptic: failure
  styles:
    grid:
      - grid-template-areas: |
          "i  circle"
          "n  n"
          "s  s"
      - grid-template-columns: repeat(2, 1fr)
      - grid-template-rows: auto repeat(2, min-content)
      - gap: 2%
      - align-items: start
    img_cell:
      - justify-content: start
      - align-items: start
    icon:
      - justify-self: start
      - height: auto
      - color: >
          [[[
            return variables.state_on 
              ? 'var( --paper-item-icon-active-color )'
              : 'rgba( 255, 255, 255, 0.3 )';
          ]]]
    name:
      - justify-self: start
      - line-height: 115%
      - letter-spacing: 0.05vw
    state:
      - justify-self: start
      - line-height: 115%
      - letter-spacing: 0.05vw

    card:
      - border-radius: var(--button-card-border-radius)
      - -webkit-tap-highlight-color: rgba(0, 0, 0, 0)
      - transition: none
      - padding: 10%
      - --mdc-ripple-color: >
          [[[
            return variables.state_on 
              ? 'rgb(0, 0, 0)' 
              : 'rgba(255, 255, 255, 0.3)';
          ]]]
      - color: >
          [[[
            return variables.state_on 
              ? 'rgba(0, 0, 0, 0.6)' 
              : 'rgba(255, 255, 255, 0.3)';
          ]]]
      - background-color: >
          [[[
            return variables.state_on 
            ? 'rgba(255, 255, 255, 0.8)' 
            : 'rgba(115, 115, 115, 0.2)';
          ]]]
  extra_styles: |
    @media screen and (max-width: 992px) {
      #name, #state {
        letter-spacing: 0.12vw;
      }
    }

    @media screen and (max-width: 1200px) {
      #name, #state {
        letter-spacing: 0.05vw;
      }
    }

    @keyframes card_bounce {
      0% {
        transform: scale(1);
      }
      15% {
        transform: scale(0.9);
      }
      25% {
        transform: scale(1);
      }
      30% {
        transform: scale(0.98);
      }
      100% {
        transform: scale(1);
      }
    }
