################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Circle
# @description :
#
################################################################################

circle:
  styles:
    custom_fields:
      circle:
        - display: initial
        - width: 88%
        - margin: -6% -6% 0 0
        - justify-self: end
        - opacity: 1
  custom_fields:
    circle: >
      [[[
        if( ['on', 'Run'].indexOf( variables.state ) !== -1 )
        { 
          const domain = entity.entity_id.split('.')[0];
          const percent = ( domain === 'switch' && variables.state ) ? 100 : variables.circle_percent;
          const value = ( undefined !== variables.circle_value ) ? variables.circle_value : percent;
          const radius = 20.5;
          const circumference = radius * 2 * Math.PI;
          return `
            <svg viewBox="0 0 50 50">
              <style>
                circle {
                  transform: rotate(-90deg);
                  transform-origin: 50% 50%;
                  stroke-dasharray: ${circumference};
                  stroke-dashoffset: ${circumference - percent / 100 * circumference};
                }
                tspan {
                  font-size: 10px;
                }
              </style>
              <circle cx="25" cy="25" r="${radius}" stroke="#b2b2b2" stroke-width="1.5" fill="none" />
              <text x="50%" y="54%" fill="#8d8e90" font-size="14" text-anchor="middle" alignment-baseline="middle" dominant-baseline="middle">${value}<tspan font-size="10">${variables.circle_value_unit}</tspan></text>
            </svg>
          `;
        }
      ]]]
