################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Details
# @description :
#
################################################################################

details:
  size: 2vw
  show_icon: false
  color: "#9da0a2"
  styles:
    card:
      - color: "#97989c"
      - width: fit-content
      - border: 0.12vw solid rgba(115, 115, 115, 0.15)
      - transition: none
      - margin: 0
      - overflow: visible
  extra_styles: |
    #name {
      color: rgba(255, 255, 255, 0.3);
      font-size: var(--footer-card-font-size);
      letter-spacing: 0.05vw;
      opacity: 1.0;
    }

    ha-icon {
      width: var(--footer-card-icon-size);
      vertical-align: 7%;
      padding-right: 0.2vw;
      color: rgba(255, 255, 255, 0.3);
      opacity: 1.0;
    }

    #card {
      padding: var(--footer-card-padding-v) var(--footer-card-padding-h);
      border-radius: var(--footer-card-border-radius);
      background: rgba(115, 115, 115, 0.20);
    }

    /* Mobile */
    @media screen and (max-width: 992px) { 
      ha-card { 
        width: 100%;
        margin: 0 2vw;
      }

      ha-icon { 
        width: calc(var(--footer-card-icon-size) * 3.5 );
      }

      #name { 
        font-size: calc(var(--footer-card-font-size) * 3.5 );
      }

      #card { 
        padding: calc(var(--footer-card-padding-v) * 3 ) calc(var(--footer-card-padding-h) * 3 );
        width: 100% !important;
      }
    }
