################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Media
# @description :
#
################################################################################

media:
  template:
    - base
    - loader
  variables:
    media_on: >
      [[[ return !entity || ['playing', 'paused'].indexOf(entity.state) !== -1; ]]]
    media_off: >
      [[[ return !entity || ['off', 'idle', 'standby', 'unknown', 'unavailable'].indexOf(entity.state) !== -1; ]]]
  tap_action:
    action: >
      [[[
        return variables.media_on
            ? 'call-service'
            : 'none';
      ]]]
    service: media_player.media_play_pause
    service_data:
      entity_id: >
        [[[
          return variables.entity_id;
        ]]]
  # double_tap_action:
  #   action: fire-dom-event
  #   browser_mod:
  #     command: popup
  #     title: >
  #       [[[
  #         return ! entity || entity.attributes.friendly_name
  #       ]]]
  #     style:
  #       hui-entities-card:
  #         $: |
  #           #states {
  #             padding-top: 0.8em;
  #           }
  #     card:
  #       type: entities
  #       entities:
  #         - type: custom:mushroom-media-player-card
  #           entity: >
  #             [[[
  #               return variables.entity_id;
  #             ]]]
  #           fill_container: false
  #           primary_info: "name"
  #           secondary_info: "state"
  #           icon_type: "icon"
  #           use_media_info: true
  #           show_volume_level: true
  #           media_controls: [on_off, previous, play_pause_stop, next]
  #           volume_controls: [volume_mute, volume_set, volume_buttons]
  #           collapsible_controls: true
