################################################################################
#
# @author      : Thomas Maxson
# @package     : Button Card Templates, Person
# @description :
#
################################################################################

person:
  template:
    - base
  state_display: >
    [[[
      if( variables.state === 'home' || variables.state === 'Home' )
      { 
        return 'Home';

      } else if( variables.state == 'not_home' )
      { 
        return 'Away';

      } else
      {
        return variables.state;

      }
    ]]]

  styles:
    card:
      - color: rgba(255, 255, 255, 0.3)
      - background-color: rgba(115, 115, 115, 0.2)
    grid:
      - grid-template-areas: |
          "icon  ."
          "n  n"
          "s  s"
    custom_fields:
      icon:
        - clip-path: circle()
        - width: 79%
        - pointer-events: none
        - display: grid
        - filter: >
            [[[
              return (variables.state === 'home' || variables.state === 'Home') ?
                'grayscale(0)' :
                'grayscale(1)';
            ]]]
  extra_styles: |
    #img-cell { display: none !important;}
  custom_fields:
    icon: >
      [[[ return entity === undefined ? null : `<img src="${states[entity.entity_id].attributes.entity_picture}" width="100%">`; ]]]

person_boolean:
  template:
    - base
  state_display: >
    [[[ return ( variables.state === 'on' ) ? 'Home' : 'Away'; ]]]
  styles:
    card:
      - color: rgba(255, 255, 255, 0.3)
      - background-color: rgba(115, 115, 115, 0.2)
    grid:
      - grid-template-areas: |
          "i  ."
          "n  n"
          "s  s"
    icon:
      - border-radius: 100%
      - clip-path: circle()
    entity_picture:
      - clip-path: circle()
      - border-radus: 100%
      - filter: >
          [[[
            return (variables.state === 'on') ?
              'grayscale(0)' :
              'grayscale(1)';
          ]]]

    custom_fields:
      circle:
        - opacity: 0

    circle: >
      [[[ return ''; ]]]
