################################################################################
#
# @author      : Thomas Maxson
# @package     : Sensors
# @description :
#
################################################################################

script:
  audio_local:
    sequence:
      # Ensure that audible notifications are allowed
      # - condition: state
      #   entity_id: input_boolean.audible_notifications_johan
      #   state: "on"
      # Ensure people is home
      # - condition: state
      #   entity_id: group.residents
      #   state: home
      # Update the media player with the one you want to use
      - service: media_player.turn_on
        entity_id: media_player.echo_dot_bedroom_4
      - delay: 00:00:05
      # This tells it to play the media and is set when the script is called
      - service: media_player.play_media
        entity_id: media_player.echo_dot_bedroom_4
        data:
          media_content_type: music
          media_content_id: >
            {{ media }}

  audio_youtube:
    sequence:
      # Ensure that audible notifications are allowed
      # - condition: state
      #   entity_id: input_boolean.audible_notifications_johan
      #   state: "on"
      # Ensure people is home
      # - condition: state
      #   entity_id: group.residents
      #   state: home
      # Update the media player with the one you want to use
      - service: media_player.turn_on
        entity_id: media_player.echo_dot_bedroom_4
      # This tells it to play the media and is set when the script is called
      - service: media_extractor.play_media
        entity_id: media_player.echo_dot_bedroom_4
        data:
          media_content_id: https://www.youtube.com/watch?v=rxxC7RJ2b_E
          media_content_type: video/youtube
