################################################################################
#
# @author      : Thomas Maxson
# @package     : Calendar
# @description : Custom calendar sensors
#
################################################################################

binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise

  - platform: tod
    name: Day
    after: sunrise
    before: sunset

  - platform: tod
    name: Early Morning
    after: sunrise
    after_offset: '-00:45'
    before: '08:00'

  - platform: tod
    name: Morning
    after: '08:00'
    before: '12:00'

  - platform: tod
    name: Afternoon
    after: '12:00'
    before: sunset
    before_offset: '-02:30'

  - platform: tod
    name: Evening
    after: sunset
    after_offset: '-02:30'
    before: '20:30'

  - platform: tod
    name: Late Evening
    after: '20:30'
    before: '23:59'

  - platform: workday
    country: US
    province: FL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

  - platform: workday
    name: Cleaning Day
    country: US
    workdays: [thu]
    excludes: [mon, tue, wed, fri, sat, sun]
    remove_holidays:
      - "New Year's Day"
      - "Memorial Day"
      - "Independence Day"
      - "Labor Day"
      - "Thanksgiving"
      - "Christmas Day"
