################################################################################
#
# @author      : Thomas Maxson
# @package     : Calendar
# @description : Custom calendar sensors
#
################################################################################

binary_sensor:
  - platform: workday
    country: US
    province: FL
    workdays: [mon, tue, wed, thu, fri]

  - platform: tod
    name: Night
    after: sunset
    before: sunrise

  - platform: tod
    name: Day
    after: sunrise
    before: sunset

  - platform: tod
    name: Quiet time
    after: "21:00"
    before: "06:00"

  - platform: tod
    name: Morning
    after: "06:00"
    before: "08:30"

  - platform: tod
    name: Midday
    after: "08:30"
    before: "17:00"

  - platform: tod
    name: Evening
    after: "17:00"
    before: "21:00"

  - platform: workday
    name: Waste Day, Solid
    country: US
    workdays: [tue, fri]
    excludes: [mon, wed, thu, sat, sun]
    remove_holidays:
      - "New Year's Day"
      - "Memorial Day"
      - "Independence Day"
      - "Labor Day"
      - "Thanksgiving"
      - "Christmas Day"

  - platform: workday
    name: Waste Day, Bulk
    country: US
    workdays: [tue]
    excludes: [mon, wed, thu, fri, sat, sun]
    remove_holidays:
      - "New Year's Day"
      - "Memorial Day"
      - "Independence Day"
      - "Labor Day"
      - "Thanksgiving"
      - "Christmas Day"

  - platform: workday
    name: Waste Day, Recycling
    country: US
    workdays: []
    excludes: [mon, tue, wed, thu, fri, sat, sun]
    remove_holidays:
      - "New Year's Day"
      - "Memorial Day"
      - "Independence Day"
      - "Labor Day"
      - "Thanksgiving"
      - "Christmas Day"

  - platform: tod
    name: Waste Take Out, Time
    after: "16:00"
    before: "22:00"

  - platform: tod
    name: Waste Bring In, Time
    after: "06:00"
    before: "16:00"
