################################################################################
#
# @author      : Thomas Maxson
# @package     : Covers
# @description :
#
################################################################################

cover:
  - platform: template
    covers:
      bedroom_1_large_curtains:
        device_class: curtain
        friendly_name: "Bedroom 1 Large Window Curtains"
        position_template: "{{ states( 'sensor.bedroom_1_large_window_curtain_position' ) }}"
        icon_template: >-
          {%- set position = states( 'sensor.bedroom_1_large_window_curtain_position' ) | round | int %}

          {%- if position <= 5 -%}
          mdi:curtains-closed
          {%- else -%}
          mdi:curtains
          {%- endif -%}
        value_template: >-
          {%- set position = states( 'sensor.bedroom_1_large_window_curtain_position' ) | round | int %}

          {%- if position <= 5 -%}
            Closed
          {%- else -%}
            Open
          {%- endif -%}
        open_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_1_large_deviceId
            command: "turnOn"
        close_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_1_large_deviceId
            command: "turnOff"
        stop_cover:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_1_large_deviceId
            command: "turnOff"
        set_cover_position:
          service: rest_command.switchbot_device_command
          data:
            deviceId: !secret switchbot_bedroom_1_large_deviceId
            command: "setPosition"
            parameter: "0,ff,{{position}}"
