################################################################################
#
# @author      : Thomas Maxson
# @package     : Customize
# @description : Modify existing components
#
################################################################################

homeassistant:
  customize:
    #
    # LIGHTS
    # --------------------------------------------------

    light.kitchen_ceiling_lights:
      friendly_name: Kitchen Ceiling Lights
      icon: hue:recessed-ceiling

    light.kitchen_light_1:
      friendly_name: Kitchen Ceiling Light, 01
      icon: bha:ceiling-downlight

    light.kitchen_light_2:
      friendly_name: Kitchen Ceiling Light, 02
      icon: bha:ceiling-downlight

    light.kitchen_light_3:
      friendly_name: Kitchen Ceiling Light, 03
      icon: bha:ceiling-downlight

    light.kitchen_light_4:
      friendly_name: Kitchen Ceiling Light, 04
      icon: bha:ceiling-downlight

    light.kitchen_light_5:
      friendly_name: Kitchen Ceiling Light, 05
      icon: bha:ceiling-downlight

    light.kitchen_light_6:
      friendly_name: Kitchen Ceiling Light, 06
      icon: bha:ceiling-downlight

    light.dining_room_chandelier:
      friendly_name: Dining Room Chandelier
      icon: bha:chandelier

    light.living_room_corner_lamp:
      friendly_name: Living Room Corner Lamp
      icon: bha:table-lamp-variant

    light.foyer_hallway_ceiling:
      friendly_name: Foyer Hallway Light
      icon: bha:dome-light

    light.foyer_entryway_ceiling:
      friendly_name: Foyer Entryway Light
      icon: hass:chandelier

    light.foyer_ceiling_ledge:
      friendly_name: Upper Ledge Lightstrip
      icon: mdi:led-strip-variant

    light.foyer_under_table:
      friendly_name: Entry Table Lightstrip
      icon: mdi:led-strip-variant

    light.laundry_ceiling_light:
      friendly_name: Laundry Ceiling Light
      icon: bha:dome-light

    light.bedroom_1_bedside_lights:
      friendly_name: Bedside Lamps
      icon: mdi:lamps

    light.bedroom_1_lamp_j:
      friendly_name: Her Bedside Lamp
      icon: mdi:lamp

    light.bedroom_1_lamp_t:
      friendly_name: His Bedside Lamp
      icon: mdi:lamp

    # light.bedroom_3_lights:
    #   friendly_name: Her Office Lights
    #   icon: mdi:lightbulb-group

    light.bedroom_4_lights:
      friendly_name: His Office Lights
      icon: mdi:lightbulb-group

    light.bedroom_4_desk_lamp:
      friendly_name: His Office Desk Lamp
      icon: mdi:lightbulb

    light.bedroom_4_lightstrip:
      friendly_name: His Office Lightstrip
      icon: mdi:led-strip-variant

    light.closet_hallway_ceiling_light:
      friendly_name: Closet Hallway
      icon: bha:dome-light

    light.bedroom_1_closet_lights:
      friendly_name: Closet Lights
      icon: mdi:lightbulb

    light.closet_hallway_light_j:
      friendly_name: Her Closet Light
      icon: mdi:lightbulb

    light.closet_hallway_light_t:
      friendly_name: His Closet Light
      icon: mdi:lightbulb

    light.foyer_exterior_entryway:
      friendly_name: Entryway
      icon: hass:globe-light

    light.garage_exterior:
      friendly_name: Garage Exterior Lights
      icon: bha:outdoor-lamp-variant

    #
    # SWITCHES
    # --------------------------------------------------

    switch.backyard_string_lights:
      friendly_name: Backyard String Lights
      icon: bha:light-string

    sensor.switch_bedroom_4_for_bedroom_4:
      device_class: light
      friendly_name: Bedroom 4 for Bedroom 4 Remote

    sensor.switch_kitchen_for_garage:
      device_class: light
      friendly_name: Kitchen for Garage Remote

    #
    # DOORS
    # --------------------------------------------------

    cover.garage_door:
      device_class: garage
      friendly_name: Garage Door
      homebridge_cover_type: garage_door

    binary_sensor.door_bedroom_1:
      device_class: door
      friendly_name: Main Bedroom Door

    binary_sensor.door_bedroom_2:
      device_class: door
      friendly_name: Guest Bedroom Door

    binary_sensor.door_bedroom_3:
      device_class: door
      friendly_name: Jess' Office Door

    binary_sensor.door_bedroom_4:
      device_class: door
      friendly_name: Tom's Office Door

    binary_sensor.door_living:
      device_class: door
      friendly_name: Living Room Sliding Glass Door

    binary_sensor.door_laundry:
      device_class: door
      friendly_name: Laundry Room Door

    binary_sensor.door_closet_hallway_j:
      device_class: door
      friendly_name: Jess' Closet Door

    binary_sensor.door_closet_hallway_t:
      device_class: door
      friendly_name: Tom's Closet Door

    #
    # OCCUPANCY
    # --------------------------------------------------

    binary_sensor.bedroom_1_occupancy:
      device_class: occupancy
      friendly_name: Main Bedroom Occupancy

    binary_sensor.bedroom_4_occupancy:
      device_class: occupancy
      friendly_name: Tom's Office Occupancy

    binary_sensor.foyer_occupancy:
      device_class: occupancy
      friendly_name: Foyer Occupancy

    binary_sensor.living_room_occupancy:
      device_class: occupancy
      friendly_name: Living Room Occupancy

    #
    # LEAK
    # --------------------------------------------------

    binary_sensor.leak_air_conditioner:
      device_class: moisture
      friendly_name: Air Conditioning Leak Sensor

    binary_sensor.leak_sink_guest_bathroom:
      device_class: moisture
      friendly_name: Guest Bathroom Sink Leak Sensor

    binary_sensor.leak_sink_half_bathroom:
      device_class: moisture
      friendly_name: Half Bathroom Sink Leak Sensor

    binary_sensor.leak_sink_kitchen:
      device_class: moisture
      friendly_name: Kitchen Sink Leak Sensor

    binary_sensor.leak_sink_main_bathroom_hers:
      device_class: moisture
      friendly_name: Main Bathroom Sink (Hers) Leak Sensor

    binary_sensor.leak_sink_main_bathroom_his:
      device_class: moisture
      friendly_name: Main Bathroom Sink (His) Leak Sensor

    binary_sensor.leak_washing_machine_laundry:
      device_class: moisture
      friendly_name: Laundry Room Leak Sensor

    #
    # BATTERY
    # --------------------------------------------------

    sensor.door_bedroom_1_battery_level:
      device_class: battery
      friendly_name: Bedroom 1 Door Battery

    sensor.door_bedroom_2_battery_level:
      device_class: battery
      friendly_name: Bedroom 2 Door Battery

    sensor.door_bedroom_3_battery_level:
      device_class: battery
      friendly_name: Bedroom 3 Door Battery

    sensor.door_bedroom_4_battery_level:
      device_class: battery
      friendly_name: Bedroom 4 Door Battery

    sensor.door_living_battery_level:
      device_class: battery
      friendly_name: Living Room Sliding Glass Door Battery

    sensor.door_laundry_battery_level:
      device_class: battery
      friendly_name: Laundry Room Door Battery

    sensor.door_closet_hallway_j_battery_level:
      device_class: battery
      friendly_name: Jess' Closet Door Battery

    sensor.door_closet_hallway_t_battery_level:
      device_class: battery
      friendly_name: Tom's Closet Door Battery

    sensor.leak_air_conditioner_battery_level:
      device_class: battery
      friendly_name: Air Conditioner Sink Leak Battery

    sensor.leak_sink_guest_bathroom_battery_level:
      device_class: battery
      friendly_name: Guest Bathroom Sink Leak Sensor Battery

    sensor.leak_sink_half_bathroom_battery_level:
      device_class: battery
      friendly_name: Half Bathroom Sink Leak Sensor Battery

    sensor.leak_sink_kitchen_battery_level:
      device_class: battery
      friendly_name: Kitchen Sink Leak Sensor Battery

    sensor.leak_sink_main_bathroom_hers_battery_level:
      device_class: battery
      friendly_name: Main Bathroom Sink (Hers) Leak Sensor Battery

    sensor.leak_sink_main_bathroom_his_battery_level:
      device_class: battery
      friendly_name: Main Bathroom Sink (His) Leak Sensor Battery

    sensor.leak_washing_machine_laundry_battery_level:
      device_class: battery
      friendly_name: Laundry Room Leak Sensor Battery

    #
    # MEDIA
    # --------------------------------------------------

    media_player.sony_bravia_tv:
      device_class: tv
      friendly_name: Television
      source_list: ["Nintendo Switch", "Nintendo Console", "AppleTV"]

    #
    # TECHNOLOGY
    # --------------------------------------------------
    #
    # HOME ASSISTANT
    # ----------------------------------------

    sensor.ha_uptime:
      friendly_name: HA Uptime
      icon: mdi:clock-start

    sensor.last_boot:
      friendly_name: Last Restart
      icon: mdi:update

    sensor.processor_use_percent:
      friendly_name: Processor
      icon: mdi:chip

    sensor.processor_temperature:
      friendly_name: Temperature
      icon: mdi:thermometer

    sensor.database:
      friendly_name: Database Size
      icon: mdi:database

    sensor.home_assistant_log:
      friendly_name: Log File Size
      icon: mdi:file-document

    #
    # MISC
    # --------------------------------------------------
    #
    # SPEEDTEST
    # ----------------------------------------

    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:speedometer

    sensor.speedtest_download:
      friendly_name: Download Speed
      icon: mdi:download
      #unit_of_measurement: "MB/s"

    sensor.speedtest_upload:
      friendly_name: Upload Speed
      icon: mdi:upload
      #unit_of_measurement: "MB/s"

    #
    # INPUTS
    # --------------------------------------------------
    #
    # INPUT SELECT
    # ----------------------------------------

    # input_select.trash_pickup_1:
    #   name: Trash Pickup, Day 1
    #   icon: mdi:delete-variant

    # input_select.trash_pickup_2:
    #   name: Trash Pickup, Day 2
    #   icon: mdi:delete-variant

    # input_select.bulk_pickup:
    #   name: Bulk Pickup
    #   icon: mdi:delete-variant

    # input_select.recycle_pickup:
    #   name: Recycle Pickup
    #   icon: mdi:delete-variant

    #
    # INPUT BOOLEAN
    # ----------------------------------------

    input_boolean.automation_daily_sunset:
      name: Daily Sunset Automation
      icon: mdi:home-automation

    input_boolean.gouda_home:
      name: Gouda is Home
      icon: mdi:dog