################################################################################
#
# @author      : Thomas Maxson
# @package     : Group
# @description :
#
################################################################################

group:
  residents:
    name: Residents
    entities:
      - person.thomas
      - person.jessica
      - person.leo
      - person.dolores

  pets:
    name: Pets
    entities:
      - input_boolean.gouda_home

  kitchen_cabinet_upper_lights:
    name: Cabinet Upper Lights
    entities:
      - light.kitchen_cabinet_upper_range
      - light.kitchen_cabinet_upper_coffee_bar

  lights_all:
    name: All Lights
    entities:
      #- light.kitchen_ceiling_lights
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.kitchen_light_5
      - light.kitchen_light_6
      - light.kitchen_cabinet_upper_range
      - light.kitchen_cabinet_upper_coffee_bar
      - light.dining_room_chandelier
      - light.living_room_corner_lamp
      - light.foyer_ceiling_ledge
      - light.foyer_under_table
      - light.foyer_entryway_ceiling
      - light.foyer_hallway_ceiling
      - light.laundry_ceiling_light
      #- light.bedroom_1_bedside_lamps
      - light.bedroom_1_lamp_j
      - light.bedroom_1_lamp_t
      - light.closet_hallway_ceiling_light
      - light.closet_hallway_light_j
      - light.closet_hallway_light_t
      - light.bedroom_4_desk_lamp
      - light.bedroom_4_lightstrip
      - light.foyer_exterior_entryway
      - light.garage_exterior
      - light.backyard_string_lights

  lights_all_interior:
    name: All Interior Lights
    entities:
      - light.kitchen_ceiling_lights
      - light.kitchen_cabinet_upper_range
      - light.kitchen_cabinet_upper_coffee_bar
      - light.dining_room_chandelier
      - light.living_room_corner_lamp
      - light.foyer_entryway_ceiling
      - light.foyer_hallway_ceiling
      - light.laundry_ceiling_light
      - light.bedroom_1_bedside_lamps
      - light.closet_hallway_ceiling_light
      - light.closet_hallway_light_t
      - light.closet_hallway_light_j
      - light.bedroom_4_desk_lamp
      - light.bedroom_4_lightstrip

  lights_all_exterior:
    name: All Exterior Lights
    entities:
      - light.foyer_exterior_entryway
      - light.garage_exterior
      - light.backyard_string_lights

  sensors_doors:
    name: Doors
    entities:
      - binary_sensor.door_front_primary
      - binary_sensor.door_garage
      - binary_sensor.door_bedroom_1
      - binary_sensor.door_bedroom_2
      - binary_sensor.door_bedroom_3
      - binary_sensor.door_bedroom_4
      - binary_sensor.door_living
      - binary_sensor.door_laundry
      - binary_sensor.door_closet_hallway_j
      - binary_sensor.door_closet_hallway_t

  sensors_doors_interior:
    name: All Interior Doors
    entities:
      - binary_sensor.door_garage
      - binary_sensor.door_bedroom_1
      - binary_sensor.door_bedroom_2
      - binary_sensor.door_bedroom_3
      - binary_sensor.door_bedroom_4
      - binary_sensor.door_laundry
      - binary_sensor.door_closet_hallway_j
      - binary_sensor.door_closet_hallway_t

  sensors_doors_exterior:
    name: All Exterior Doors
    entities:
      - binary_sensor.door_front_primary
      - binary_sensor.door_garage
      - binary_sensor.door_living

  # sensors_doors_notify:
  #   name: Notfiy Door Actions
  #   entities:
  #     - binary_sensor.door_bedroom_1
  #     - binary_sensor.door_bedroom_2
  #     - binary_sensor.door_bedroom_3
  #     - binary_sensor.door_bedroom_4
  #     - binary_sensor.door_living
  #     - binary_sensor.door_laundry
  #     - binary_sensor.door_front_primary

  sensors_leak:
    name: Leak Sensors
    entities:
      - binary_sensor.leak_air_conditioner
      - binary_sensor.leak_sink_guest_bathroom
      - binary_sensor.leak_sink_half_bathroom
      - binary_sensor.leak_sink_kitchen
      - binary_sensor.leak_sink_main_bathroom_hers
      - binary_sensor.leak_sink_main_bathroom_his
      - binary_sensor.leak_washing_machine_laundry

  # DELVELOPER NOTE:
  # Low Battery Level Notification Group is managed within an automation.
  # Manage monitored entities within that automation.
  # sensors_battery_levels:
  #   name: Battery Levels
  #   entities:
  #     - sensor.front_door_battery_level
  #     # Aqara Door/Window Sensors
  #     - sensor.door_bedroom_1_battery_level
  #     - sensor.door_bedroom_2_battery_level
  #     - sensor.door_bedroom_3_battery_level
  #     - sensor.door_bedroom_4_battery_level
  #     - sensor.door_living_battery_level
  #     - sensor.door_laundry_battery_level
  #     - sensor.door_closet_hallway_j_battery_level
  #     - sensor.door_closet_hallway_t_battery_level
  #     # Aqara Leak Sensors
  #     - sensor.leak_air_conditioner_battery_level
  #     - sensor.leak_sink_guest_bathroom_battery_level
  #     - sensor.leak_sink_half_bathroom_battery_level
  #     - sensor.leak_sink_kitchen_battery_level
  #     - sensor.leak_sink_main_bathroom_hers_battery_level
  #     - sensor.leak_sink_main_bathroom_his_battery_level
  #     - sensor.leak_washing_machine_laundry_battery_level
  #     # Aqara Motion Sensors
  #     - sensor.motion_laundry_battery_level
  #     # Aqara Buttons
  #     #- sensor.switch_foyer
  #     #- sensor.switch_garage
  #     #- sensor.switch_office_tom
