################################################################################
#
# @author      : Thomas Maxson
# @package     : Input Helpers
# @description : Manually added helper inputs
#
################################################################################
#
# INPUT, BOOLEAN
# --------------------------------------------------

input_boolean:
  debug_texts:
    name: Debug Texts
    icon: hass:test-tube