################################################################################
#
# @author      : Thomas Maxson
# @package     : Integrations
# @description : Configuration for various integrations and addons
#
################################################################################
#
# MariaDB
# ----------------------------------------

recorder:
  db_url: !secret recorder_db_url
  exclude:
    entity_globs:
      - sensor.browser_*