################################################################################
#
# @author      : Thomas Maxson
# @package     : Integrations
# @description : Configuration for various integrations and addons
#
################################################################################
#
# MariaDB
# ----------------------------------------

recorder:
  db_url: !secret recorder_db_url
  exclude:
    entity_globs:
      - sensor.browser_*

#
# InfluxDB
# ----------------------------------------

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#
# Google Calendar
# ----------------------------------------

# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_client_secret

#
# Switchbot
# ----------------------------------------

# switch:
#   - platform: switchbot
#     mac: "EF:BD:30:E1:94:15"
#     name: Bedroom 1, Large Window Left
#   - platform: switchbot
#     mac: "C7:69:2D:3E:FD:50"
#     name: Bedroom 1, Large Window Right

rest_command:
  switchbot_device_command:
    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
    method: post
    content_type: "application/json"
    headers:
      Authorization: !secret switchbot_api
    payload: '{"command": "{{ command }}","parameter": "{{ parameter }}"}'

sensor:
  - platform: rest
    name: "Bedroom 1 Large Window Curtain Position"
    resource: !secret switchbot_bedroom_1_large_status_url
    method: GET
    scan_interval: 30
    headers:
      Authorization: !secret switchbot_api
      Content-Type: "application/json"
    value_template: >-
      {% if 'unknown' != value_json.body.slidePosition %}
        {% if value_json.body.slidePosition > 95 %}
          0
        {% elif value_json.body.slidePosition < 5 %}
          100
        {% else %}
          {{ 100 - value_json.body.slidePosition }}
        {%- endif -%}
      {%- else -%}
        0
      {%- endif -%}
    json_attributes_path: "$.body"
    json_attributes:
      - deviceId
      - deviceType
      - hubDeviceId
      - calibrate
      - group
      - moving
      - slidePosition
