################################################################################
#
# @author      : Thomas Maxson
# @package     : Group, Lights
# @description :
#
################################################################################

light:
  - platform: group
    name: Kitchen Ceiling Lights
    unique_id: kitchen_ceiling_lights
    entities:
      - light.kitchen_light_1
      - light.kitchen_light_2
      - light.kitchen_light_3
      - light.kitchen_light_4
      - light.kitchen_light_5
      - light.kitchen_light_6

  # NOTE: This does NOT work with current button card setup
  # NOTE: Shows "NaN" for light brightness value
  # NOTE: Syncing of lights occurs in Node RED
  # - platform: group
  #   name: Kitchen Cabinet Upper Lights
  #   unique_id: kitchen_cabinet_upper_lights
  #   entities:
  #     - light.kitchen_cabinet_upper_coffee_bar
  #     - light.kitchen_cabinet_upper_range

  - platform: group
    name: Foyer Ceiling Lights
    #  unique_id: foyer_ceiling_lights
    entities:
      - light.foyer_entryway_ceiling
      - light.foyer_hallway_ceiling

  - platform: group
    name: Bedroom 1 Bedside Lamps
    unique_id: bedroom_1_bedside_lamps
    entities:
      - light.bedroom_1_lamp_j
      - light.bedroom_1_lamp_t

  - platform: group
    name: Bedroom 1 Closet Lights
    unique_id: bedroom_1_closet_lights
    entities:
      - light.closet_hallway_light_j
      - light.closet_hallway_light_t

  - platform: group
    name: Bedroom 4 Lights
    unique_id: bedroom_4_lights
    entities:
      - light.bedroom_4_desk_lamp
      - light.bedroom_4_lightstrip
