################################################################################
#
# @author      : Thomas Maxson
# @package     : Sensors
# @description :
#
################################################################################

sensor:
  # - platform: filesize
  #   file_paths:
  #     - /config/home-assistant.log

  # MariaDB recorder DB size sensor
  # DEPRECATED IN 2022.6
  # - platform: sql
  #   db_url: !secret recorder_db_url
  #   queries:
  #     - name: MariaDB Database Size
  #       query: >
  #         SELECT table_schema "database", Round( Sum( data_length + index_length ) / POWER( 1024, 2 ), 1 )
  #         "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;
  #       column: value
  #       unit_of_measurement: MB

  # InfluxDB DB size sensor
  - platform: influxdb
    host: !secret influxdb_host
    port: !secret influxdb_port
    username: !secret influxdb_username
    password: !secret influxdb_password
    queries:
      - name: InfluxDB Database Size
        unit_of_measurement: MB
        value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
        group_function: mean
        measurement: '"monitor"."shard"'
        database: _internal
        where: 'time > now() - 1m AND "database"=''home_assistant'''
        field: diskBytes
        # unit_of_measurement: MB
        # value_template: "{{ (value | float / 1024 /1024) | round(1) }}"
        # group_function: sum
        # measurement: '"monitor"."shard"'
        # database: _internal
        # where: "time > now() - 10s"
        # field: diskBytes

  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0