################################################################################
#
# @author      : Thomas Maxson
# @package     : Sensors
# @description :
#
################################################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0