################################################################################
#
# @author      : Thomas Maxson
# @package     : Sensors
# @description :
#
################################################################################

# sensor:
#   - platform: systemmonitor
#     resources:
#       - type: last_boot
#       - type: ipv4_address
#         arg: eth0
#       - type: ipv6_address
#         arg: eth0
#       - type: processor_use
#       - type: processor_temperature
#       - type: memory_free
#       - type: memory_use_percent
#       - type: disk_use_percent
#         arg: /
#       - type: disk_use
#       - type: disk_free
#       - type: throughput_network_in
#         arg: eth0
#       - type: throughput_network_out
#         arg: eth0

sensor:
  - platform: template
    sensors:
      custom_door_closet_hallway_j:
        friendly_name: "Jess' Closet Door"
        value_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_hers', 'on' ) -%}
            Open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_hers', 'off' ) -%}
            Closed
          {%- else -%}
            Unknown
          {%- endif -%}
        icon_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_hers', 'on' ) -%}
          mdi:door-sliding-open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_hers', 'off' ) -%}
          mdi:door-sliding
          {%- else -%}
          mdi:cloud-question
          {%- endif -%}

      custom_door_closet_hallway_t:
        friendly_name: "Tom's Closet Door"
        value_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_his', 'on' ) -%}
            Open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_his', 'off' ) -%}
            Closed
          {%- else -%}
            Unknown
          {%- endif -%}
        icon_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_his', 'on' ) -%}
          mdi:door-sliding-open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_his', 'off' ) -%}
          mdi:door-sliding
          {%- else -%}
          mdi:cloud-question
          {%- endif -%}

fan:
  - platform: template
    fans:
      custom_garage_fan:
        friendly_name: "Garage Fan"
        turn_on:
          service: light.turn_on
          entity_id: light.garage_fan
        turn_off:
          service: light.turn_off
          entity_id: light.garage_fan
        value_template: >-
          {%- if is_state( 'light.garage_fan', 'on' ) -%}
            On
          {%- elif is_state( 'light.garage_fan', 'off' ) -%}
            Off
          {%- else -%}
            Unknown
          {%- endif -%}