################################################################################
#
# @author      : Thomas Maxson
# @package     : Template Sensors
# @description :
#
################################################################################

sensor:
  - platform: template
    sensors:
      is_week_even:
        friendly_name: "Is Week Even"
        value_template: >-
          {%- set output = ( ( ( now().strftime( '%W' ) ) | int ) % 2 ) == 0 %}
          {{ iif( ( True == output ), 'on', 'off' ) }}
        icon_template: >-
          {%- set output = ( ( ( now().strftime( '%W' ) ) | int ) % 2 ) == 0 %}
          {{ iif( ( True == output ), 'mdi:calendar-check', 'mdi:calendar-remove' ) }}

      is_week_odd:
        friendly_name: "Is Week Odd"
        value_template: >-
          {%- set output = ( ( ( now().strftime( '%W' ) ) | int ) % 2 ) == 1 %}
          {{ iif( ( True == output ), 'on', 'off' ) }}
        icon_template: >-
          {%- set output = ( ( ( now().strftime( '%W' ) ) | int ) % 2 ) == 1 %}
          {{ iif( ( True == output ), 'mdi:calendar-check', 'mdi:calendar-remove' ) }}

      custom_laundry_machine_state:
        friendly_name: "Laundry Machine Status"
        value_template: >-
          {%- set status_washer = states( 'sensor.laundry_washer_machine_state' ) -%}
          {%- set status_dryer  = states( 'sensor.laundry_dryer_machine_state' ) -%}

          {%- if status_washer == 'Run' or status_dryer == 'Run' -%}
            on
          {%- else -%}
            off
          {%- endif -%}
        icon_template: >-
          {%- set status_washer = states( 'sensor.laundry_washer_machine_state' ) -%}
          {%- set status_dryer  = states( 'sensor.laundry_dryer_machine_state' ) -%}

          {%- if status_washer == 'Run' or status_dryer == 'Run' -%}
            mdi:washing-machine
          {%- else -%}
            mdi:washing-machine-off
          {%- endif -%}

      custom_door_closet_hallway_j:
        friendly_name: "Jess' Closet Door"
        value_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_j', 'on' ) -%}
            Open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_j', 'off' ) -%}
            Closed
          {%- else -%}
            Unknown
          {%- endif -%}
        icon_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_j', 'on' ) -%}
          mdi:door-sliding-open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_j', 'off' ) -%}
          mdi:door-sliding
          {%- else -%}
          mdi:cloud-question
          {%- endif -%}

      custom_door_closet_hallway_t:
        friendly_name: "Tom's Closet Door"
        value_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_t', 'on' ) -%}
            Open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_t', 'off' ) -%}
            Closed
          {%- else -%}
            Unknown
          {%- endif -%}
        icon_template: >-
          {%- if is_state( 'binary_sensor.door_closet_hallway_t', 'on' ) -%}
          mdi:door-sliding-open
          {%- elif is_state( 'binary_sensor.door_closet_hallway_t', 'off' ) -%}
          mdi:door-sliding
          {%- else -%}
          mdi:cloud-question
          {%- endif -%}

      custom_fire_tablet_battery:
        #device_class: battery
        friendly_name: Battery Level
        unit_of_measurement: "%"
        value_template: >-
          {{ states( 'sensor.fire_tablet_battery' ) }}
        icon_template: >-
          {%- set battery_level = states( 'sensor.fire_tablet_battery' ) -%}
          {%- set battery_round = ( battery_level | int(0) / 10 ) | int(0) * 10 -%}

          {%- if battery_level == 0 -%}
            mdi:battery-alert
          {%- elif battery_round >= 80 -%}
            mdi:battery
          {%- elif battery_round <= 20 -%}
            mdi:battery-outline
          {%- else -%}
            mdi:battery-{{ battery_round }}
          {%- endif -%}

      household_notifications_snooze_countdown:
        device_class: timestamp
        value_template: >-
          {%- set state = states( 'timer.household_activity_snooze' ) %}
          {%- set duration = state_attr( 'timer.household_activity_snooze', 'duration' ) %}
          {%- set n = now().timestamp() %}
          {%- set h = '00' | int %}
          {%- set m = '00' | int %}
          {%- set s = '00' | int %}

          {%- if state not in [ 'idle', 'unknown', 'unavailable' ] %}
            {%- set h, m, s = duration.split( ':' ) | list | map( 'int' ) %}
          {%- endif %}

          {{ ( n + h * 60 * 60 + m * 60 + s ) | timestamp_custom( '%Y-%m-%dT%H:%M:%S-00:00', false ) }}

      garage_door_open_snooze_countdown:
        device_class: timestamp
        value_template: >-
          {%- set state = states( 'timer.garage_open_snooze' ) %}
          {%- set duration = state_attr( 'timer.garage_open_snooze', 'duration' ) %}
          {%- set n = now().timestamp() %}
          {%- set h = '00' | int %}
          {%- set m = '00' | int %}
          {%- set s = '00' | int %}

          {%- if state not in [ 'idle', 'unknown', 'unavailable' ] %}
            {%- set h, m, s = duration.split( ':' ) | list | map( 'int' ) %}
          {%- endif %}

          {{ ( n + h * 60 * 60 + m * 60 + s ) | timestamp_custom( '%Y-%m-%dT%H:%M:%S-00:00', false ) }}

      doorbell_motion_snooze_countdown:
        device_class: timestamp
        value_template: >-
          {%- set state = states( 'timer.doorbell_motion_snooze' ) %}
          {%- set duration = state_attr( 'timer.doorbell_motion_snooze', 'duration' ) %}
          {%- set n = now().timestamp() %}
          {%- set h = '00' | int %}
          {%- set m = '00' | int %}
          {%- set s = '00' | int %}

          {%- if state not in [ 'idle', 'unknown', 'unavailable' ] %}
            {%- set h, m, s = duration.split( ':' ) | list | map( 'int' ) %}
          {%- endif %}

          {{ ( n + h * 60 * 60 + m * 60 + s ) | timestamp_custom( '%Y-%m-%dT%H:%M:%S-00:00', false ) }}

      front_door_unlocked_snooze_countdown:
        device_class: timestamp
        value_template: >-
          {%- set state = states( 'timer.front_door_unlocked_snooze' ) %}
          {%- set duration = state_attr( 'timer.front_door_unlocked_snooze', 'duration' ) %}
          {%- set n = now().timestamp() %}
          {%- set h = '00' | int %}
          {%- set m = '00' | int %}
          {%- set s = '00' | int %}

          {%- if state not in [ 'idle', 'unknown', 'unavailable' ] %}
            {%- set h, m, s = duration.split( ':' ) | list | map( 'int' ) %}
          {%- endif %}

          {{ ( n + h * 60 * 60 + m * 60 + s ) | timestamp_custom( '%Y-%m-%dT%H:%M:%S-00:00', false ) }}

      # fire_tablet_last_app_start_formatted:
      #   #device_class: timestamp
      #   friendly_name: Last App Restart
      #   icon_template: mdi:clock-outline
      #   value_template: >
      #     {% set timestamp = states.sensor.fire_tablet_last_app_start.last_updated %}
      #     {{ relative_time( timestamp ) }}

      fire_tablet_ram_used_memory:
        icon_template: mdi:memory
        unit_of_measurement: MB
        value_template: >-
          {%- set ignore = [ 'unknown', 'unavailable' ] -%}
          {%- set total_memory = states( 'sensor.fire_tablet_total_memory' ) | int( 0 ) -%}
          {%- set free_memory  = states( 'sensor.fire_tablet_free_memory' ) | int( 0 ) -%}

          {%- if total_memory not in ignore and total_memory not in ignore %}
            {%- set used_memory = ( total_memory - free_memory ) -%}
            {%- if used_memory > 0 and total_memory > 0 %}
              {{ used_memory / total_memory * 100 }}
            {%- else %}
              Unknown
            {%- endif %}
          {%- else %}
            Unknown
          {%- endif %}

      # Count interior lights switched ON
      total_lights_on:
        friendly_name: Total Lights On
        icon_template: mdi:lightbulb
        value_template: >-
          {% set state = 'on' %}
          {% set ns = namespace( count = 0 ) %}

          {% for light in state_attr( 'light.lights_all', 'entity_id' ) if is_state( light, state ) %}
            {% set ns.count = ns.count + 1 %}
          {% endfor %}

          {{ ns.count | int }}

      # Count Doors that are OPEN
      total_doors_open:
        friendly_name: Total Doors Open
        icon_template: mdi:door-open
        value_template: >-
          {% set state = 'on' %}
          {% set device = 'door' %}
          {{ states.binary_sensor 
            | selectattr( 'attributes.device_class', 'defined' ) 
            | selectattr( 'attributes.device_class', 'eq', device ) 
            | selectattr( 'state', 'eq', state ) 
            | map( attribute = 'entity_id' ) 
            | reject( 'in', [ 'binary_sensor.door_front_primary', 'binary_sensor.door_garage', 'binary_sensor.door_living' ] ) 
            | list | length }}

template:
  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /5
    sensor:
      - name: "Laundry Washer Combined Details"
        icon: mdi:washing-machine
        state: >-
          {{ states( 'sensor.laundry_washer_machine_state' ) }}
        attributes:
          original_time: >-
            {{ states( 'input_text.laundry_washer_original_duration' ) }}
          time_remaining: >-
            {{ states( 'sensor.laundry_washer_time_remaining' ) }}
          cycle_type: >-
            {{ states( 'sensor.laundry_washer_sub_cycle' ) }}
          cycle_end: >-
            {{ states( 'binary_sensor.laundry_washer_end_of_cycle' ) }}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /5
    sensor:
      - name: "Laundry Dryer Combined Details"
        icon: mdi:tumble-dryer
        state: >-
          {{ states( 'sensor.laundry_dryer_machine_state' ) }}
        attributes:
          original_time: >-
            {{ states( 'input_text.laundry_dryer_original_duration' ) }}
          time_remaining: >-
            {{ states( 'sensor.laundry_dryer_time_remaining' ) }}
          cycle_type: >-
            {{ states( 'sensor.laundry_dryer_sub_cycle' ) }}
          cycle_end: >-
            {{ states( 'binary_sensor.laundry_dryer_end_of_cycle' ) }}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /30
    sensor:
      - name: "Days Until, Waste Day - Solid"
        icon: mdi:trash-can-outline
        state: >-
          {%- set ignore = [ 'unknown', 'unavailable' ] -%}

          {%- set entity = 'schedule.waste_bring_in_solid' %}
          {%- set nextEvent = state_attr( entity, 'next_event' ) %}

          {%- if entity in ignore %}
            -----

          {%- else %}
            {%- if 'on' == states( entity ) %}
              Now
            {%- else %}
              {%- set date_today = as_timestamp( now() ) | timestamp_custom( '%F' ) %}
              {%- set date_tomorrow = ( as_timestamp( now() + timedelta( days = 1 ) ) ) | timestamp_custom( '%F' ) %}
              {%- set date_nextEvent = as_timestamp( nextEvent ) | timestamp_custom( '%F' ) %}

              {%- set daysUntil = ( ( as_timestamp( date_nextEvent ) - as_timestamp( date_today ) ) | int /60/1440 ) | round( 0 ) | string %}

              {%- if date_today == date_nextEvent %}
                Today

              {%- elif date_tomorrow == date_nextEvent %}
                Tomorrow

              {%- else %}
                {{ iif( ( '1' == daysUntil ), daysUntil + ' day away', daysUntil + ' days away' ) }}

              {%- endif %}
            {%- endif %}
          {%- endif %}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /30
    sensor:
      - name: "Days Until, Waste Day - Bulk"
        icon: mdi:forest
        state: >-
          {%- set ignore = [ 'unknown', 'unavailable' ] -%}

          {%- set entity = 'schedule.waste_bring_in_bulk' %}
          {%- set nextEvent = state_attr( entity, 'next_event' ) %}

          {%- if entity in ignore %}
            -----

          {%- else %}
            {%- if 'on' == states( entity ) %}
              Now
            {%- else %}
              {%- set date_today = as_timestamp( now() ) | timestamp_custom( '%F' ) %}
              {%- set date_tomorrow = ( as_timestamp( now() + timedelta( days = 1 ) ) ) | timestamp_custom( '%F' ) %}
              {%- set date_nextEvent = as_timestamp( nextEvent ) | timestamp_custom( '%F' ) %}

              {%- set daysUntil = ( ( as_timestamp( date_nextEvent ) - as_timestamp( date_today ) ) | int /60/1440 ) | round( 0 ) | string %}

              {%- if date_today == date_nextEvent %}
                Today

              {%- elif date_tomorrow == date_nextEvent %}
                Tomorrow

              {%- else %}
                {{ iif( ( '1' == daysUntil ), daysUntil + ' day away', daysUntil + ' days away' ) }}

              {%- endif %}
            {%- endif %}
          {%- endif %}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /30
    sensor:
      - name: "Days Until, Waste Day - Recycle"
        icon: mdi:recycle
        state: >-
          {%- set ignore = [ 'unknown', 'unavailable' ] -%}

          {%- set entity = 'schedule.waste_bring_in_recycle' %}
          {%- set nextEvent = state_attr( entity, 'next_event' ) %}

          {%- if entity in ignore %}
            -----

          {%- else %}
            {%- if 'on' == states( entity ) %}
              Now
            {%- else %}
              {%- set date_today = as_timestamp( now() ) | timestamp_custom( '%F' ) %}
              {%- set date_tomorrow = ( as_timestamp( now() + timedelta( days = 1 ) ) ) | timestamp_custom( '%F' ) %}
              {%- set date_nextEvent = as_timestamp( nextEvent ) | timestamp_custom( '%F' ) %}

              {%- set daysUntil = ( ( as_timestamp( date_nextEvent ) - as_timestamp( date_today ) ) | int /60/1440 ) | round( 0 ) | string %}

              {%- if date_today == date_nextEvent %}
                Today

              {%- elif date_tomorrow == date_nextEvent %}
                Tomorrow

              {%- else %}
                {{ iif( ( '1' == daysUntil ), daysUntil + ' day away', daysUntil + ' days away' ) }}

              {%- endif %}
            {%- endif %}
          {%- endif %}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every XX seconds
      - platform: time_pattern
        seconds: /30
    sensor:
      - name: "Days Until, Cleaning Day"
        icon: mdi:spray-bottle
        state: >-
          {%- set ignore = [ 'unknown', 'unavailable' ] -%}

          {%- set entity = 'calendar.casamaxson_cleaning_schedule' %}
          {%- set eventStart = state_attr( entity, 'start_time' ) | as_timestamp %}
          {%- set eventEnd   = state_attr( entity, 'end_time' ) | as_timestamp %}

          {%- set untilDays = ( ( eventStart - now().replace( hour = 0, minute = 0, second = 0, microsecond = 0 ).timestamp() ) / 86400 ) | round( 0 ) | string %}

          {%- set untilMinStart = ( ( eventStart - now().timestamp() ) / 60 ) | int %}
          {%- set untilMinEnd   = ( ( eventEnd - now().timestamp() ) / 60 ) | int %}

          {%- if entity in ignore %}
            -----

          {%- else %}
            {%- if untilMinStart <= 0 and untilMinEnd >= 0 %}
              Now
            
            {%- elif untilDays == '0' %}
              Today
            
            {%- elif untilDays == '1' %}
              Tomorrow
            
            {%- else %}
              {{ iif( ( '1' == untilDays ), untilDays + ' day away', untilDays + ' days away' ) }}
            
            {%- endif %}
          {%- endif %}

  - trigger:
      # Update on Home Assistant startup
      - platform: homeassistant
        event: start
      # Update on Template reload
      - platform: event
        event_type: event_template_reloaded
      # Update every minute
      - platform: time_pattern
        hours: "00"
        minutes: "/01"
        seconds: "00"
    sensor:
      - name: "Automation Daily Status"
        state: >-
          {%- set offset = ( 45 * 60 ) %}
          {%- set next_sunset     = as_timestamp( states.sun.sun.attributes.next_setting ) %}
          {%- set modified_sunset = ( next_sunset - offset ) | int %}
          {%- set ts_next_sunset  = modified_sunset | timestamp_custom( '%H%M%S' ) | int %}
          {%- set ts_current      = as_timestamp( now() ) | timestamp_custom( '%H%M%S' ) | int %}

          {%- if( is_state( 'input_boolean.automation_daily_sunset', 'on' ) ) %}
            Active
          {%- elif( ts_current > ts_next_sunset ) %}
            Complete
          {%- else %}
            Runs at {{ modified_sunset | timestamp_custom( '%I:%M %p' ) }}
          {%- endif %}
        icon: >-
          {%- set offset = ( 45 * 60 ) %}
          {%- set next_sunset     = as_timestamp( states.sun.sun.attributes.next_setting ) %}
          {%- set modified_sunset = ( next_sunset - offset ) | int %}
          {%- set ts_next_sunset  = modified_sunset | timestamp_custom( '%H%M%S' ) | int %}
          {%- set ts_current      = as_timestamp( now() ) | timestamp_custom( '%H%M%S' ) | int %}

          {%- if( is_state( 'input_boolean.automation_daily_sunset', 'on' ) ) %}
          mdi:clock-alert-outline
          {%- elif( ts_current > ts_next_sunset ) %}
          mdi:clock-check-outline
          {%- else %}
          mdi:clock-outline
          {%- endif %}
