################################################################################
#
# @author      : Thomas Maxson
# @package     : Weather
# @description :
#
################################################################################

sensor:
  - platform: weatheralerts
    state: FL
    zone: 71
    county: 11
