################################################################################
#
# @author      : Thomas Maxson
# @package     : Zigbee2MQTT
# @description :
#
################################################################################

input_boolean:
  zigbee2mqtt_allow_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

# Timer for joining time remaining (60 sec = 1 min)
timer:
  zigbee2mqtt_allow_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

mqtt:
  sensor:
    # Sensor for monitoring the bridge state
    - name: Zigbee2mqtt Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless
    # Sensor for Showing the Zigbee2mqtt Version
    - name: Zigbee2mqtt Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.version }}"
      icon: mdi:zigbee
    # Sensor for Showing the Coordinator Version
    - name: Zigbee2mqtt Coordinator Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.coordinator }}"
      icon: mdi:chip

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    trigger:
      platform: state
      entity_id: input_boolean.zigbee2mqtt_allow_join
      to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "true"
      - service: timer.start
        data:
          entity_id: timer.zigbee2mqtt_allow_join
  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
      - entity_id: input_boolean.zigbee2mqtt_allow_join
        platform: state
        to: "off"
    action:
      - data:
          payload: "false"
          topic: zigbee2mqtt/bridge/config/permit_join
        service: mqtt.publish
      - data:
          entity_id: timer.zigbee2mqtt_allow_join
        service: timer.cancel
  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee2mqtt_allow_join
    action:
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/permit_join
          payload: "false"
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.zigbee2mqtt_allow_join
