################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Helpers
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Helpers
    #timeout: 15000
    style: >
      --popup-max-width: calc( 385px + 385px );
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              .: |
                #root { overflow: hidden;}
              hui-entities-card:
                $: |
                  .card-content {
                    padding: 1.5em 1.5em 0;
                    margin: -2em 0 1em;
                  }

                  /* Desktop */
                  @media screen and (min-width: 992px) { 
                    .card-content { 
                      border-right: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      border-left: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      margin-right: -1px;
                      margin-left: -1px;
                    }
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 2, 385px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a column_b'
          mediaquery:
            # Tablet and down
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 2, 1fr )
              grid-template-areas: |
                'column_a'
                'column_b'
        cards:
          - type: entities
            view_layout:
              grid-area: column_a
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              # - entity: input_boolean.home_away_mode
              #   name: Home Away Mode

              - type: section
                label: Evening Automations
              - entity: sensor.evening_automations_status
                name: Status

              - entity: input_boolean.evening_automations_run
                name: Run at Sunset
              - type: conditional
                conditions:
                  - entity: input_boolean.evening_automations_run
                    state: "on"
                row:
                  entity: input_button.trigger_evening_automations_run
                  name: Run Sunset Now

              - entity: input_boolean.evening_automations_reset
                name: Run at Bedtime
              - type: conditional
                conditions:
                  - entity: input_boolean.evening_automations_reset
                    state: "on"
                row:
                  entity: input_button.trigger_evening_automations_reset
                  name: Run Bedtime Now

              - type: section
                label: Laundry Reminders
              - entity: input_boolean.reminder_laundry_complete_washer
                name: Washer Complete
              - entity: input_boolean.reminder_laundry_complete_dryer
                name: Dryer Complete

          - type: entities
            view_layout:
              grid-area: column_b
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Snoozed Household Activity
              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_household_activity
                    state: "on"
                row:
                  entity: input_boolean.snooze_household_activity
                  name: Snoozed Indefinite

              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_household_activity
                    state: "off"
                row:
                  entity: timer.snooze_household_activity
                  name: Snooze Countdown

              - type: section
                label: Snoozed Garage Door Left Open
              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_garage_open
                    state: "on"
                row:
                  entity: input_boolean.snooze_garage_open
                  name: Snoozed Indefinite
              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_garage_open
                    state: "off"
                row:
                  entity: timer.snooze_garage_open
                  name: Snooze Countdown

              - type: section
                label: Snoozed Front Door Unlocked
              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_front_door_unlocked
                    state: "on"
                row:
                  entity: input_boolean.snooze_front_door_unlocked
                  name: Snoozed Indefinite
              - type: conditional
                conditions:
                  - entity: input_boolean.snooze_front_door_unlocked
                    state: "off"
                row:
                  entity: timer.snooze_front_door_unlocked
                  name: Snooze Countdown

              # - type: section
              #   label: Snoozed Doorbell Motion Detected
              # - type: conditional
              #   conditions:
              #     - entity: input_boolean.snooze_doorbell_motion
              #       state: "on"
              #   row:
              #     entity: input_boolean.snooze_doorbell_motion
              #     name: Snoozed Indefinite
              # - type: conditional
              #   conditions:
              #     - entity: input_boolean.snooze_doorbell_motion
              #       state: "off"
              #   row:
              #     entity: timer.snooze_doorbell_motion
              #     name: Snooze Countdown
