################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Helpers
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Helpers
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content { 
        width: calc(385px + 385px);
        max-width: 90vw;
        transition: none;
      }

      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        :host .content {
          width: 100vw;
          max-width: none;
          overflow-x: hidden;
        }
      }

    layout-card:
      $grid-layout$:
        $: |
          #root {
            margin-right: 0;
            margin-left: 0;
          }

        hui-entities-card:
          $: |
            ha-card { 
              border-radius: 0;
              animation: border 1s forwards;
            }

            @keyframes border {
              0%, 100% {
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

            /* Mobile Devices */
            @media screen and (max-width: 992px) { 
              ha-card {
                width: 100vw;
                animation: none;
              }
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
    cards:
      - type: entities
        view_layout:
          grid-area: column_a
        show_header_toggle: false
        #title: Column A Title
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - entity: input_boolean.home_away_mode
            name: Home Away Mode

          - type: conditional
            conditions:
              - entity: input_boolean.manual_override_foyer_exterior_entryway
                state: "on"
            row:
              entity: input_boolean.manual_override_foyer_exterior_entryway
              name: Foyer Exterior, Override

          - type: section
            label: Automation Status
          - entity: sensor.automation_daily_status
            name: Daily, In Evening
          - entity: input_boolean.automation_daily_sunset
            name: Evening Automations

      - type: entities
        view_layout:
          grid-area: column_b
        show_header_toggle: false
        title: Snoozed Notifications
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Household Activity

          - type: conditional
            conditions:
              - entity: input_boolean.household_activity_snooze_indefinite
                state: "on"
            row:
              entity: input_boolean.household_activity_snooze_indefinite
              name: Snoozed Indefinite
          - type: conditional
            conditions:
              - entity: input_boolean.household_activity_snooze_today
                state: "on"
            row:
              entity: input_boolean.household_activity_snooze_today
              name: Snoozed for Today
          - type: conditional
            conditions:
              - entity: timer.household_activity_snooze
                state: "idle"
            row:
              entity: timer.household_activity_snooze
              name: Snooze Timer
          - type: conditional
            conditions:
              - entity: timer.household_activity_snooze
                state_not: "idle"
            row:
              entity: timer.household_activity_snooze_countdown
              name: Snooze Countdown

          - type: section
            label: Garage Door Left Open
          - type: conditional
            conditions:
              - entity: input_boolean.garage_open_snooze_indefinite
                state: "on"
            row:
              entity: input_boolean.garage_open_snooze_indefinite
              name: Snoozed Indefinite
          - type: conditional
            conditions:
              - entity: input_boolean.garage_open_snooze_today
                state: "on"
            row:
              entity: input_boolean.garage_open_snooze_today
              name: Snoozed for Today
          - type: conditional
            conditions:
              - entity: timer.garage_open_snooze
                state: "idle"
            row:
              entity: timer.garage_open_snooze
              name: Snooze Timer
          - type: conditional
            conditions:
              - entity: timer.garage_open_snooze
                state_not: "idle"
            row:
              entity: timer.garage_open_snooze_countdown
              name: Snooze Countdown

          - type: section
            label: Front Door Unlocked
          - type: conditional
            conditions:
              - entity: input_boolean.front_door_unlocked_snooze_indefinite
                state: "on"
            row:
              entity: input_boolean.front_door_unlocked_snooze_indefinite
              name: Snoozed Indefinite
          - type: conditional
            conditions:
              - entity: input_boolean.front_door_unlocked_snooze_today
                state: "on"
            row:
              entity: input_boolean.front_door_unlocked_snooze_today
              name: Snoozed for Today
          - type: conditional
            conditions:
              - entity: timer.front_door_unlocked_snooze
                state: "idle"
            row:
              entity: timer.front_door_unlocked_snooze
              name: Snooze Timer
          - type: conditional
            conditions:
              - entity: timer.front_door_unlocked_snooze
                state_not: "idle"
            row:
              entity: sensor.front_door_unlocked_snooze_countdown
              name: Snooze Countdown

          - type: section
            label: Doorbell Motion Detected
          - type: conditional
            conditions:
              - entity: input_boolean.doorbell_motion_snooze_indefinite
                state: "on"
            row:
              entity: input_boolean.doorbell_motion_snooze_indefinite
              name: Snoozed Indefinite
          - type: conditional
            conditions:
              - entity: input_boolean.doorbell_motion_snooze_today
                state: "on"
            row:
              entity: input_boolean.doorbell_motion_snooze_today
              name: Snoozed for Today
          - type: conditional
            conditions:
              - entity: timer.doorbell_motion_snooze
                state: "idle"
            row:
              entity: timer.doorbell_motion_snooze
              name: Snooze Timer
          - type: conditional
            conditions:
              - entity: timer.doorbell_motion_snooze
                state_not: "idle"
            row:
              entity: sensor.doorbell_motion_snooze_countdown
              name: Snooze Countdown
