################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Input Helpers
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Input Helpers
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
  card:
    type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - type: section
            label: Automation Flags
          - entity: input_boolean.automation_daily_sunset
            name: Evening Automations

          - type: section
            label: Doorbell Notifications
          - entity: timer.doorbell_motion_snooze
            name: Snooze Duration
          - type: conditional
            conditions:
              - entity: timer.doorbell_motion_snooze
                state: "active"
            row:
              entity: sensor.doorbell_motion_snooze_countdown
              name: Snooze Countdown
