action: fire-dom-event
browser_mod:
  command: popup
  title: Input Helpers
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    hui-vertical-stack-card:
      $hui-entities-card$: |
        #states {
          padding-top: 0.5em;
          padding-bottom: 1.2em;
        }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(1, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'general'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'general'
    cards:
      - type: entities
        view_layout:
          grid-area: general
        title: Settings
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
              width: 100%;
            }
        entities:
          - entity: input_select.day_pickup_trash_a
            name: Trash Pickup, Day 1
          - entity: input_select.day_pickup_trash_b
            name: Trash Pickup, Day 2
          - entity: input_select.day_pickup_bulk_trash
            name: Bulk Trash Pickup
          - entity: input_select.day_pickup_recycle
            name: Recycle Pickup
