################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Input Helpers
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Input Helpers
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
  card:
    type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - type: section
            label: Trash Day(s) of the Week
          - entity: input_select.waste_trash_day_a
            name: Day A
          - entity: input_select.waste_trash_day_b
            name: Day B

          - type: section
            label: Bulk Trash Day(s) of the Week
          - entity: input_select.waste_bulk_day_a
            name: Day A
          #- entity: input_select.waste_bulk_day_b
          #  name: Day B

          - type: section
            label: Recycling Day(s) of the Week
          - entity: input_select.waste_recycle_day_a
            name: Day A
          - entity: input_select.waste_recycle_day_b
            name: Day B

          - type: section
            label: Take Out Reminder Window
          - entity: input_datetime.waste_reminder_take_out_time_start
            name: Start Time
          - entity: input_datetime.waste_reminder_take_out_time_end
            name: End Time

          - type: section
            label: Bring In Reminder Window
          - entity: input_datetime.waste_reminder_bring_in_time_start
            name: Start Time
          - entity: input_datetime.waste_reminder_bring_in_time_end
            name: End Time
