################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Input Helpers
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Input Helpers
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
  card:
    type: vertical-stack
    cards:
      - type: entities
        title: Settings
        show_header_toggle: false
        entities:
          - entity: input_select.day_pickup_trash_a
            name: Trash Pickup, Day 1
          - entity: input_select.day_pickup_trash_b
            name: Trash Pickup, Day 2
          - entity: input_select.day_pickup_bulk_trash
            name: Bulk Trash Pickup
          - entity: input_select.day_pickup_recycle
            name: Recycle Pickup
