action: fire-dom-event
browser_mod:
  command: popup
  title: >
    [[[ return entity.attributes.friendly_name; ]]]
  card:
    type: entities
    entities:
      - type: custom:light-popup-card
        entity: >
          [[[ return entity.entity_id ]]]
        icon: none
        hideIcon: true
        fullscreen: false
        brightnessWidth: 130px
        brightnessHeight: 360px
        borderRadius: 1.7em
        sliderColor: "#c7c7c7"
        sliderTrackColor: rgba(25, 25, 25, 0.9)
        displayType: slider
        style: >
          #popup { 
            margin-top: 30px;
            margin-bottom: 46px;
          }

      - type: custom:hui-horizontal-stack-card
        style: >
          #root {
            justify-content: center;
            margin-top: 16px;
            margin-bottom: 30px;
          }
        cards:
          - type: custom:button-card
            view_layout:
              grid-area: color_cool
            styles:
              card:
                - background-color: "#ffefe1"
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: >
                  [[[ return entity.entity_id ]]]
                color_temp: 250
            template: color_light
          - type: custom:button-card
            view_layout:
              grid-area: color_neutral
            styles:
              card:
                - background: "#ffdfc6"
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: >
                  [[[ return entity.entity_id ]]]
                color_temp: 375
            template: color_light
          - type: custom:button-card
            view_layout:
              grid-area: color_warm
            styles:
              card:
                - background: "#ffcda6"
            tap_action:
              action: call-service
              service: light.turn_on
              service_data:
                entity_id: >
                  [[[ return entity.entity_id ]]]
                color_temp: 500
            template: color_light
          - type: custom:button-card
            view_layout:
              grid-area: color_picker
            styles:
              card:
                [
                  background:
                    "radial-gradient(circle, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0) 80%),
                    conic-gradient(rgb(120, 39, 230), rgb(230, 34, 231), rgb(228, 5, 136), rgb(228, 25, 25),
                    rgb(229, 105, 30), rgb(232, 226, 46), rgb(125, 230, 41), rgb(52, 232, 40), rgb(51, 231, 92),
                    rgb(52, 232, 224), rgb(32, 125, 229), rgb(18, 39, 229), rgb(120, 39, 230))",
                ]
            tap_action:
              action: fire-dom-event
              browser_mod:
                command: popup
                title: >
                  [[[ return entity.attributes.friendly_name ]]]
                card:
                  type: custom:light-entity-card
                  entity: >
                    [[[ return entity.entity_id ]]]
                  brightness: true
                  color_temp: true
                  full_width_sliders: false
                  hide_header: true
                  show_slider_percent: true
                  smooth_color_wheel: true
                  persist_features: true
                  consolidate_entities: false
            template: color_light
