action: fire-dom-event
browser_mod:
  command: popup
  title: Jessica's Details
  style:
    hui-vertical-stack-card:
      # $hui-history-graph-card$: |
      #   .content {
      #     padding: 0.2em 1.7em 1.2em 1.7em !important;
      #   }
      $: |
        button-card {
          align-self: center;
          padding: 0.2em 0 2.3em 0;
        }
      $hui-map-card:
        $: |
          mwc-icon-button {
            color: var(--primary-color);
          }
          ha-card {
            border-radius: 0;
            animation: border 1s forwards;
          }
          @keyframes border {
            0%, 100% {
              border-top: 2px solid #1a1a1a;
            }
          }
        $ha-map$: |
          #map {
            background-color: #191919 !important;
          }
          .leaflet-control-attribution {
            display: none;
          }
          .leaflet-bar a {
            background-color: rgba(47, 51, 51, 0.9) !important;
            color: #9da0a2 !important;
          }
          a.leaflet-control-zoom-in {
            border-bottom: 1px solid #181818 !important;
          }
          .leaflet-pane.leaflet-tile-pane {
            filter: contrast(85%);
          }
  card:
    type: vertical-stack
    cards:
      - type: entities
        card_mod:
          class: content
        entities:
          - entity: person.jessica
            secondary_info: last-changed

      # - type: history-graph
      #   entities:
      #     - entity: person.jessica

      # - type: glance
      #   show_state: false
      #   entities:

      #     - entity: device_tracker.thomas_iphone
      #       name: Router
      #       icon: mdi:wifi
      #       style: &state |
      #         state-badge {
      #           color: {{ '#3182b7' if is_state(config.entity, 'home') else '#3c3f3f' }};
      #         }

      #     - entity: device_tracker.sanja_bluetooth
      #       name: Bluetooth
      #       icon: mdi:bluetooth
      #       style: *state

      #     - entity: device_tracker.sanjas_iphone_ios
      #       name: Position
      #       icon: custom:iphone-modern
      #       style: *state

      - type: custom:button-card
        name: Find this iPhone
        icon: mdi:bell-ring
        template: icon_name
        tap_action:
          confirmation:
            text: Are you sure you want to ping this device?
          action: call-service
          service: notify.mobile_app_jess_iphone
          service_data:
            title: Find my iPhone
            message: Here I am.
            data:
              push:
                sound:
                  name: alarm.caf
                  critical: 1
                  volume: 1

      - type: map
        default_zoom: 16
        dark_mode: true
        entities:
          - person.jessica
