################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Person (Leonardo)
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Leonardo's Details
    #timeout: 15000
    style: >
      --popup-max-width: calc( 400px );
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              .: |
                #root { overflow: hidden;}
              hui-entities-card:
                $: |
                  .card-content {
                    padding: 0 1.5em 0;
                    margin: 0;
                  }
              decluttering-card:
                $: |
                  #root button-card { 
                    margin: 2vw auto 1vw;
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 1, 400px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a'
          mediaquery:
            # Tablet and down
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 1, 1fr )
              grid-template-areas: |
                'column_a'
        cards:
          - type: entities
            card_mod:
              class: column
            entities:
              - entity: person.leo
                secondary_info: last-changed
              # - entity: sensor.leo_personal_iphone_steps
              #   name: Step Count

          # - type: history-graph
          #   entities:
          #     - entity: person.leonardo

          - type: custom:decluttering-card
            template: popup_person_find_device
            variables:
              - name: Find this iPhone (Personal)
              - device: notify.mobile_app_leonardos_iphone

          - type: custom:decluttering-card
            template: popup_person_find_device
            variables:
              - name: Find this iPhone (Work)
              - device: notify.mobile_app_leoair

          - type: custom:decluttering-card
            template: popup_person_notifications
            variables:
              - notify_general: input_boolean.app_notify_leo
              - notify_info: input_boolean.app_notify_leo_alert_info
              - notify_warning: input_boolean.app_notify_leo_alert_warning
              - notify_critical: input_boolean.app_notify_leo_alert_critical
              - notify_activity: input_boolean.app_notify_leo_alert_activity
              - notify_activity_door_interior: input_boolean.app_notify_leo_alert_activity_door_interior
              - notify_activity_door_exterior: input_boolean.app_notify_leo_alert_activity_door_exterior
              - notify_activity_person_locations: input_boolean.app_notify_leo_alert_activity_person_location

          - type: map
            default_zoom: 16
            dark_mode: true
            entities:
              - person.leo
            card_mod:
              style:
                .: |
                  #root {
                    height: 25em;
                    padding-bottom: 0 !important;
                  }
                  ha-icon-button {
                    color: var(--primary-color);
                    zoom: 140%;
                    margin-left: -0.2em;
                  }
                  ha-card {
                    border-top: 2px solid #1a1a1a;
                    border-radius: 0;
                    transition: none;
                    margin-bottom: -4px !important;
                  }
                ha-map$: |
                  #map {
                    background-color: #191919 !important;
                  }
                  .leaflet-control-attribution {
                    display: none;
                  }
                  .leaflet-bar a {
                    background-color: rgba(115, 123, 124, 0.2) !important;
                    color: #9da0a2 !important;
                    backdrop-filter: blur(0.25em);
                    zoom: 140%;
                  }
                  a.leaflet-control-zoom-in {
                    border-bottom: 1px solid #181818 !important;
                  }
                  .leaflet-pane.leaflet-tile-pane {
                    filter: invert(0.95) grayscale(0.95) contrast(95%);
                  }
