################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Person (Dolores)
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Dolores' Details
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    hui-vertical-stack-card:
      # $hui-history-graph-card$: |
      #   .content {
      #     padding: 0.2em 1.7em 1.2em 1.7em !important;
      #   }
      $: |
        button-card {
          align-self: center;
          padding: 0.2em 0 2.3em 0;
        }
      $hui-map-card:
        $: |
          #root {
            height: 27em;
            padding-bottom: 0 !important;
          }
          mwc-icon-button {
            color: var(--primary-color);
          }
          ha-card {
            border-radius: 0;
            animation: border 1s forwards;
          }
          @keyframes border {
            0%, 100% {
              border-top: 2px solid #1a1a1a;
            }
          }
        $ha-map$: |
          #map {
            background-color: #191919 !important;
          }
          .leaflet-control-attribution {
            display: none;
          }
          .leaflet-bar a {
            background-color: rgba(47, 51, 51, 0.9) !important;
            color: #9da0a2 !important;
          }
          a.leaflet-control-zoom-in {
            border-bottom: 1px solid #181818 !important;
          }
          .leaflet-pane.leaflet-tile-pane {
            filter: contrast(85%);
          }
  card:
    type: vertical-stack
    cards:
      - type: entities
        card_mod:
          class: content
        entities:
          - entity: person.dolores
            secondary_info: last-changed

      # - type: history-graph
      #   entities:
      #     - entity: person.dolores

      - type: custom:button-card
        name: Find this iPhone
        icon: mdi:bell-ring
        template: icon_name
        tap_action:
          confirmation:
            text: Are you sure you want to ping this device?
          action: call-service
          service: notify.mobile_app_tatis_iphone
          service_data:
            title: Find my iPhone
            message: Here I am.
            data:
              push:
                sound:
                  name: alarm.caf
                  critical: 1
                  volume: 1

      - type: custom:decluttering-card
        template: popup_person_notifications
        variables:
          - notify_general: 'input_boolean.app_notify_dolores'
          - notify_info: 'input_boolean.app_notify_dolores_alert_info'
          - notify_warning: 'input_boolean.app_notify_dolores_alert_warning'
          - notify_critical: 'input_boolean.app_notify_dolores_alert_critical'
          - notify_activity: 'input_boolean.app_notify_dolores_alert_activity'
          - notify_activity_door_interior: 'input_boolean.app_notify_dolores_alert_activity_door_interior'
          - notify_activity_door_exterior: 'input_boolean.app_notify_dolores_alert_activity_door_exterior'
          - notify_activity_person_locations: 'input_boolean.app_notify_dolores_alert_activity_person_location'

      - type: map
        default_zoom: 16
        dark_mode: true
        entities:
          - person.dolores
