################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Person (Jessica)
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Jessica's Details
  style:
    $: |
      @media screen and (max-width: 992px) {
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
          border-radius: 0 !important;
        }
      }
    hui-vertical-stack-card:
      $decluttering-card:
        $: |
          #root button-card {
            margin: 1vw auto;
          }
      $hui-map-card:
        $: |
          #root {
            height: 27em;
            padding-bottom: 0 !important;
          }
          mwc-icon-button {
            color: var(--primary-color);
          }
          ha-card {
            border-radius: 0;
            animation: border 1s forwards;
          }
          @keyframes border {
            0%, 100% {
              border-top: 2px solid #1a1a1a;
            }
          }
        $ha-map$: |
          #map {
            background-color: #191919 !important;
          }
          .leaflet-control-attribution {
            display: none;
          }
          .leaflet-bar a {
            background-color: rgba(115, 123, 124, 0.2) !important;
            color: #9da0a2 !important;
            backdrop-filter: blur(0.25em);
          }
          a.leaflet-control-zoom-in {
            border-bottom: 1px solid #181818 !important;
          }
          .leaflet-pane.leaflet-tile-pane {
            filter: invert(0.95) grayscale(0.95) contrast(95%);
          }
  card:
    type: vertical-stack
    cards:
      - type: entities
        card_mod:
          class: content
        entities:
          - entity: person.jessica
            secondary_info: last-changed
          - entity: sensor.jessica_maxson_s_iphone_steps
            name: Step Count

      # - type: history-graph
      #   entities:
      #     - entity: person.jessica

      - type: custom:decluttering-card
        template: popup_person_find_device
        variables:
          - device: notify.mobile_app_jess_iphone

      - type: custom:decluttering-card
        template: popup_person_notifications
        variables:
          - notify_general: input_boolean.app_notify_jess
          - notify_info: input_boolean.app_notify_jess_alert_info
          - notify_warning: input_boolean.app_notify_jess_alert_warning
          - notify_critical: input_boolean.app_notify_jess_alert_critical
          - notify_activity: input_boolean.app_notify_jess_alert_activity
          - notify_activity_door_interior: input_boolean.app_notify_jess_alert_activity_door_interior
          - notify_activity_door_exterior: input_boolean.app_notify_jess_alert_activity_door_exterior
          - notify_activity_person_locations: input_boolean.app_notify_jess_alert_activity_person_location

      - type: map
        default_zoom: 16
        dark_mode: true
        entities:
          - person.jessica
