################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Pets
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Pets
    #timeout: 15000
    style: >
      --popup-max-width: calc( 400px );
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              .: |
                #root { overflow: hidden;}
              hui-entities-card:
                $: |
                  .card-content {
                    padding: 1.5em 1.5em 0;
                    margin: -2em 0 1em;
                  }

                  /* Desktop */
                  @media screen and (min-width: 992px) { 
                    .card-content { 
                      border-right: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      border-left: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      margin-right: -1px;
                      margin-left: -1px;
                    }
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 1, 400px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a'
          mediaquery:
            # Tablet and down
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 1, 1fr )
              grid-template-areas: |
                'column_a'
        cards:
          - type: entities
            card_mod:
              class: column
            entities:
              - type: section
                label: Pet Status
                card_mod:
                  style: |
                    .label { display: none;}
              - entity: input_boolean.status_dog_gouda
                name: Gouda is Home
              # - entity: input_boolean.dog_walrus_status
              #   name: Walrus is Home
              # - entity: input_boolean.dog_lady_mimi_status
              #   name: Lady Mimi is Home
