################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Sidebar Controls
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Sidebar
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
  card:
    type: vertical-stack
    cards:
      - type: entities
        entities:
          - type: section
            label: Garbage

          - entity: input_boolean.garbage_bins_out
            name: Garbage Bins Taken Out
          - entity: input_boolean.garbage_bins_in
            name: Garbage Bins Brought In

          - type: section
            label: Sidebar Display

          - entity: input_boolean.sidebar_display_holidays
            name: Display Upcoming Holidays
          - entity: input_boolean.sidebar_display_celebrations
            name: Display Upcoming Celebrations
          - entity: input_boolean.sidebar_display_weather_forecast
            name: Display Weather Forecast
          - entity: input_boolean.sidebar_display_lights_on
            name: Display Lights On
          - entity: input_boolean.sidebar_display_open_doors
            name: Display Open Doors
          - entity: input_boolean.sidebar_display_garbage_reminder
            name: Display Garbage Reminders
