################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Household Overview
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Household Overview
  large: false
  style:
    .: |
      :host .content {
        overflow-x: hidden;
      }

      /* Desktop */
      @media screen and (min-width: 992px) { 
        :host .content { 
          width: calc(385px + 385px + 385px);
          max-width: 90vw;
        }
      }

    layout-card:
      $grid-layout$:
        .: |
          @media screen and (min-width: 992px) { 
            #root {
              margin-top: 0 !important;
              margin-right: 0 !important;
              margin-left: 0 !important;
            }
          }

        hui-entities-card:
          $: |
            ha-card .card-content { 
              padding-top: 0 !important;
              margin-top: -16px;
            }

            /* Mobile */
            @media screen and (max-width: 992px) { 
              ha-card .card-content { 
                width: 90vw;
              }
            }

            /* Desktop */
            @media screen and (min-width: 992px) { 
              ha-card .card-content { 
                border-right: 1px solid var(--entities-divider-color, var(--divider-color));
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'group_a group_b group_c'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'group_a'
            'group_b'
            'group_c'
    cards:
      - type: entities
        view_layout:
          grid-area: group_a
        #title: Column A Title
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Kitchen
          - entity: light.kitchen_ceiling_lights
            name: Ceiling
            secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.kitchen_cabinet_upper_coffee_bar
                state_not: "unavailable"
              - entity: light.kitchen_cabinet_upper_range
                state_not: "unavailable"
              - entity: input_boolean.sync_cabinet_above_lights
                state: "on"
            row:
              entity: light.kitchen_cabinet_upper_coffee_bar
              name: Above Cabinets
              icon: hass:led-strip-variant
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.kitchen_cabinet_upper_range
                state_not: "unavailable"
              - entity: input_boolean.sync_cabinet_above_lights
                state: "off"
            row:
              entity: light.kitchen_cabinet_upper_range
              name: Above Cabinets, Range
              icon: hass:led-strip-variant
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.kitchen_cabinet_upper_coffee_bar
                state_not: "unavailable"
              - entity: input_boolean.sync_cabinet_above_lights
                state: "off"
            row:
              entity: light.kitchen_cabinet_upper_coffee_bar
              name: Above Cabinets, Coffee Bar
              icon: hass:led-strip-variant
              secondary_info: brightness

          - type: section
            label: Common Areas
          - entity: light.dining_room_chandelier
            name: Dining Room, Chandelier
            icon: bha:chandelier
            secondary_info: brightness
          - entity: light.living_room_corner_lamp
            name: Living Room, Corner
            icon: bha:table-lamp-variant
            secondary_info: brightness

          - type: section
            label: Foyer
          - type: conditional
            conditions:
              - entity: light.foyer_ceiling_lights
                state_not: "unavailable"
              - entity: input_boolean.sync_foyer_lights
                state: "on"
            row:
              entity: light.foyer_ceiling_lights
              name: Ceiling Lights
              icon: bha:dome-light
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.foyer_entryway_ceiling
                state_not: "unavailable"
              - entity: input_boolean.sync_foyer_lights
                state: "off"
            row:
              entity: light.foyer_entryway_ceiling
              name: Entryway
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.foyer_hallway_ceiling
                state_not: "unavailable"
              - entity: input_boolean.sync_foyer_lights
                state: "off"
            row:
              entity: light.foyer_hallway_ceiling
              name: Hallway
              secondary_info: brightness

            secondary_info: brightness
          - entity: light.foyer_ceiling_ledge
            name: Upper Ledge
            secondary_info: brightness
          - entity: light.foyer_under_table
            name: Under Table
            secondary_info: brightness

      - type: entities
        view_layout:
          grid-area: group_b
        #title: Column B Title
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Main Bedroom
          - entity: cover.bedroom_1_large_curtains
            name: Large Window
          - entity: light.bedroom_1_bedside_lamps
            name: Bedside Lamps
            secondary_info: brightness
          - entity: light.closet_hallway_ceiling_light
            name: Closet Hallway
            icon: bha:dome-light
            secondary_info: brightness
          - entity: light.closet_hallway_light_j
            name: Closet (Hers)
            secondary_info: brightness
          - entity: light.closet_hallway_light_t
            name: Closet (His)
            secondary_info: brightness

          - type: section
            label: Offices
          - type: conditional
            conditions:
              - entity: light.bedroom_4_lights
                state_not: "unavailable"
              - entity: input_boolean.sync_bedroom_4_lights
                state: "on"
            row:
              entity: light.bedroom_4_lights
              name: His Office, Lights
              icon: hue:desk-lamp
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.bedroom_4_desk_lamp
                state_not: "unavailable"
              - entity: input_boolean.sync_bedroom_4_lights
                state: "off"
            row:
              entity: light.bedroom_4_desk_lamp
              name: His Office, Desk Lamp
              secondary_info: brightness

          - type: conditional
            conditions:
              - entity: light.bedroom_4_lightstrip
                state_not: "unavailable"
              - entity: input_boolean.sync_bedroom_4_lights
                state: "off"
            row:
              entity: light.bedroom_4_lightstrip
              name: His Office, Lightstrip
              secondary_info: brightness

          - type: section
            label: Other
          - entity: light.laundry_ceiling_light
            name: Laundry Room Ceiling
            icon: bha:dome-light
            secondary_info: brightness
          - entity: light.laundry_hallway_light
            name: Laundry Room Hallway
            icon: bha:dome-light
            secondary_info: brightness
          - entity: switch.garage_light
            name: Garage Ceiling
            icon: hass:lightbulb

      - type: entities
        view_layout:
          grid-area: group_c
        #title: Column C Title
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Exterior
          - entity: light.foyer_exterior_entryway
            name: Front Door Entryway
            icon: hass:globe-light
            secondary_info: brightness
          - entity: light.garage_exterior
            name: Garage Exterior
            icon: bha:outdoor-lamp-variant
            secondary_info: brightness
          - entity: light.backyard_string_lights
            name: Backyard String Lights
            icon: bha:light-string

          - type: section
            label: Exterior Doors
          - entity: lock.front_door
            name: Front Door
          - entity: cover.garage_door
            name: Garage Door
          - entity: binary_sensor.door_living
            name: Living Room Sliding Glass
