################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Household
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Household Details
  style:
    $: |
      .mdc-dialog .mdc-dialog__content { 
        padding: 0 !important;
      }
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    .: |
      :host .content {
        margin: 0 !important;
        width: calc( 385px * 2 );
        max-width: 90vw;
      }

      @media screen and (max-width: 992px) {
        :host .content {
          width: 100%;
          max-width: none;
        }
      }
    layout-card:
      $grid-layout$:
        .: |
          :host {
            padding: 0;
          }

          #root { 
            margin: -1px !important;
            overflow-x: hidden;
          }

          hui-entities-card { border-left: 1px solid rgba(0, 0, 0, 0.3);}

          @media screen and (max-width: 992px) {
            hui-entities-card { 
              border-top: 1px solid rgba(0, 0, 0, 0.3);
              border-left: 0;
            }
          }

        hui-entities-card:
          $: |
            ha-card {
              padding: 0 !important;
              border-radius: 0;
              margin: 0;
            }

            .card-header,
            .card-content { 
              padding: 1.5em 1.5em !important;
              margin: 0 !important;
            }

            .card-header {
              padding-top: 1em !important;
              padding-bottom: 0 !important;
            }

            @media screen and (max-width: 992px) {
              ha-card { 
                width: 100%;
                width: 100vw;
              }
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
    cards:
      - type: entities
        view_layout:
          grid-area: column_a
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
              width: 100%;
            }
        entities:
          - type: section
            label: Lights, Interior

          - entity: light.kitchen_ceiling_lights
            name: Kitchen, Ceiling
            #icon: bha:ceiling-downlight
            secondary_info: brightness
          - entity: light.dining_room_chandelier
            name: Dining Room, Chandelier
            icon: bha:chandelier
            secondary_info: brightness
          - entity: light.living_room_corner_lamp
            name: Living Room, Corner Lamp
            icon: bha:table-lamp-variant
            secondary_info: brightness

          - entity: light.foyer_hallway_ceiling
            name: Foyer, Hallway
            secondary_info: brightness
          - entity: light.foyer_entryway_ceiling
            name: Foyer, Entryway
            secondary_info: brightness
          - entity: light.foyer_ceiling_ledge
            name: Foyer, Ledge
            secondary_info: brightness
          - entity: light.foyer_under_table
            name: Foyer, Under Table
            secondary_info: brightness
          #- entity: light.bedroom_1_bedside_lamps
          #  name: Main Bedroom, Bedside Lamps
          #  secondary_info: brightness
          - entity: light.bedroom_1_lamp_j
            name: Main Bedroom, Her Bedside Lamp
            secondary_info: brightness
          - entity: light.bedroom_1_lamp_t
            name: Main Bedroom, His Bedside Lamp
            secondary_info: brightness
          - entity: light.closet_hallway_ceiling_light
            name: Closet Hallway, Ceiling Light
            icon: bha:dome-light
            secondary_info: brightness
          - entity: light.closet_hallway_light_j
            name: Closet, Her Side
            secondary_info: brightness
          - entity: light.closet_hallway_light_t
            name: Closet, His Side
            secondary_info: brightness
          - entity: light.bedroom_4_desk_lamp
            name: His Office, Desk Lamp
            secondary_info: brightness
          - entity: light.bedroom_4_lightstrip
            name: His Office, Light Strip
            secondary_info: brightness
          - entity: light.laundry_ceiling_light
            name: Laundry Room, Ceiling Light
            icon: bha:dome-light
            secondary_info: brightness

          - type: section
            label: Lights, Exterior

          - entity: light.foyer_exterior_entryway
            name: Front Door Entry
            icon: hass:globe-light
            secondary_info: brightness
          - entity: light.garage_exterior
            name: Garage Exterior
            icon: bha:outdoor-lamp-variant
            secondary_info: brightness
          - entity: switch.backyard_string_lights
            name: Backyard String Lights
            icon: bha:light-string

      - type: entities
        view_layout:
          grid-area: column_b
        #title: Doors
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
              width: 100%;
            }
        entities:
          - type: section
            label: Doors

          - entity: cover.garage_door
            name: Garage Door
          - entity: lock.front_door
            name: Front Door
          - type: divider
          - entity: binary_sensor.door_bedroom_1
            name: Main Bedroom
          - entity: binary_sensor.door_bedroom_2
            name: Guest Bedroom
          - entity: binary_sensor.door_bedroom_3
            name: Her Office
          - entity: binary_sensor.door_bedroom_4
            name: His Office
          - entity: binary_sensor.door_living
            name: Living Room Sliding Glass
          - entity: binary_sensor.door_laundry
            name: Laundry Room
          #- type: divider
          - entity: sensor.custom_door_closet_hallway_j
            #- entity: binary_sensor.door_closet_hallway_j
            name: Her Closet
          - entity: sensor.custom_door_closet_hallway_t
            #- entity: binary_sensor.door_closet_hallway_t
            name: His Closet

          # - type: section
          #   label: Occupany

          # - entity: binary_sensor.foyer_occupancy
          # - entity: binary_sensor.bedroom_1_occupancy
          # - entity: binary_sensor.bedroom_4_occupancy
          # - entity: binary_sensor.living_room_occupancy

          - type: section
            label: Motion Sensors

          - entity: binary_sensor.motion_laundry
            name: Laundry Room
            icon: hass:motion-sensor

          - type: section
            label: Other

          - entity: media_player.sony_bravia_tv
          - entity: light.tablet_plug
            name: Kitchen, Tablet Plug
            #icon: bha:apple-tv
            icon: hass:tablet
          - entity: light.bedroom_4_media_plug
            name: His Office, Media Plug
            #icon: bha:apple-tv
            icon: hass:apple
