################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Settings
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Settings
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    .: |
      :host .content {
        width: calc(385px + 385px);
        max-width: 90vw;
      }

      @media screen and (max-width: 992px) {
        :host .content {
          width: 100%;
          max-width: none;
        }
      }
    layout-card:
      $grid-layout$:
        hui-entities-card:
          $: |
            .card-content {
              padding: 1.5em 2.7em 2.3em 2em;
            }
            ha-card {
              animation: border 1s forwards;
              border-radius: 0;
            }
            @keyframes border {
              0%, 100% {
                border-right: 1px solid rgba(0, 0, 0, 0.3);
              }
            }
            /* phone */
            @media screen and (max-width: 992px) {
              ha-card {
                animation: none;
              }
            }
          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
    cards:
      - type: entities
        view_layout:
          grid-area: column_a
        #title: Settings
        show_header_toggle: false
        entities:
          - type: section
            label: Waste Pickup
          - entity: sensor.days_until_waste_solid
            name: Solid Waste
          - entity: sensor.days_until_waste_bulk
            name: Bulk Waste
          - entity: sensor.days_until_waste_recycling
            name: Recycling

          - type: section
            label: Sync Lights
          - entity: input_boolean.sync_foyer_lights
            name: Foyer, Entryway & Hallway

          - type: conditional
            conditions:
              - entity: input_boolean.automation_daily_sunset
                state: "on"
            row:
              entity: input_boolean.automation_daily_sunset
              name: Daily Automations Ran

          - type: section
            label: Vacation Mode
          - entity: input_boolean.vacation_mode
            name: Activate
          - type: conditional
            conditions:
              - entity: input_boolean.vacation_mode
                state: "on"
            row:
              entity: input_boolean.vacation_mode_running
              name: Light Is On

      - type: entities
        view_layout:
          grid-area: column_b
        #title: Notifications
        show_header_toggle: false
        entities:
          - type: section
            label: Auditory Notifications
          - entity: input_boolean.household_notify
            name: Household Can Speak
          - type: section
            label: Recieve Push Notifications
          - entity: input_boolean.app_notify
            name: All Can Recieve
          - entity: input_boolean.app_notify_tom
            name: Tom Can Recieve
          - entity: input_boolean.app_notify_jess
            name: Jess Can Recieve
