################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Temperature
# @description :
#
# Color Tool   : https://material.io/resources/color/#!/?view.left=0&view.right=0
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Temperature
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    .: |
      :host .content {
        width: calc(385px + 385px);
        max-width: 90vw;
      }

      @media screen and (max-width: 992px) {
        :host .content {
          width: 100%;
          max-width: none;
        }
      }
    layout-card:
      $grid-layout$:
        hui-entities-card:
          $: |
            .card-content {
              padding: 1.5em 2.7em 2.3em 2em;
            }
            ha-card {
              animation: border 1s forwards;
              border-radius: 0;
            }
            @keyframes border {
              0%, 100% {
                border-right: 1px solid rgba(0, 0, 0, 0.3);
              }
            }
            /* phone */
            @media screen and (max-width: 992px) {
              ha-card {
                animation: none;
              }
            }
          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b'
        'column_c column_c'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
            'column_c'

    cards:
      - type: thermostat
        entity: climate.ecobee
        view_layout:
          grid-area: column_a
        show_header_toggle: false

      - type: entities
        view_layout:
          grid-area: column_b
        show_header_toggle: false
        entities:
          - entity: sensor.foyer_humidity
            name: Humidity

          - type: divider

          - entity: sensor.foyer_temperature
            name: Foyer
            style: |
              :host {
                --paper-item-icon-color: #e53935;
              }
          - entity: sensor.living_room_temperature
            name: Living Room
            style: |
              :host {
                --paper-item-icon-color: #fb8c00;
              }
          - entity: sensor.bedroom_1_temperature
            name: Main Bedroom
            style: |
              :host {
                --paper-item-icon-color: #fdd835;
              }
          - entity: sensor.bedroom_4_temperature
            name: Office, His
            style: |
              :host {
                --paper-item-icon-color: #4caf50;
              }
          - entity: sensor.temp_attic_temperature
            name: Attic
            style: |
              :host {
                --paper-item-icon-color: #757575;
              }

      - type: entities
        view_layout:
          grid-area: column_c
        show_header_toggle: false
        entities:
          - type: divider
        footer:
          type: custom:mini-graph-card
          entities:
            - entity: sensor.bedroom_4_temperature
              color: "#4caf50"
              name: Office, His
            - entity: sensor.bedroom_1_temperature
              color: "#fdd835"
              name: Main Bedroom
            - entity: sensor.living_room_temperature
              color: "#fb8c00"
              name: Living Room
            - entity: sensor.foyer_temperature
              color: "#e53935"
              name: Foyer
          line_width: 2
          hour24: true
          group: false
          align_state: left
          hours_to_show: 24
          show:
            {
              fill: fade,
              name: false,
              icon: false,
              state: false,
              legend: false,
            }
          tap_action:
            action: none
