################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Systems
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: System Details
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content {
        overflow-x: hidden;
      }

      /* Desktop */
      @media screen and (min-width: 992px) { 
        :host .content { 
          width: calc(385px + 385px + 385px);
          max-width: 90vw;
        }
      }

    layout-card:
      $grid-layout$:
        .: |
          @media screen and (min-width: 992px) { 
            #root {
              margin-top: 0 !important;
              margin-right: 0 !important;
              margin-left: 0 !important;
            }
          }

        hui-entities-card:
          $: |
            ha-card .card-content { 
              padding-top: 0 !important;
              margin-top: -16px;
            }

            /* Mobile */
            @media screen and (max-width: 992px) { 
              ha-card .card-content { 
                width: 90vw;
              }
            }

            /* Desktop */
            @media screen and (min-width: 992px) { 
              ha-card .card-content { 
                border-right: 1px solid var(--entities-divider-color, var(--divider-color));
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'homeassistant tablet network'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'homeassistant'
            'tablet'
            'network'
    cards:
      - type: entities
        view_layout:
          grid-area: homeassistant
        #title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Home Assistant

          - entity: sensor.processor_temperature
          - type: custom:bar-card
            width: 55%
            height: 2em
            decimal: 0
            unit_of_measurement: "%"
            positions:
              icon: outside
              indicator: "off"
              name: outside
            severity:
              - color: "#303435"
                from: 0
                to: 89
              - color: "#6d2525"
                from: 90
                to: 100
            entity_row: true
            entities:
              - entity: sensor.processor_use_percent

          - type: divider

          - entity: sensor.home_assistant_log_size
          - entity: sensor.mariadb_database_size
            icon: mdi:database
          - entity: sensor.influxdb_database_size
            icon: mdi:database

          - type: divider

          - entity: input_button.home_assistant_restart
            icon: mdi:restart
            name: Restart System
            tap_action:
              action: call-service
              service: homeassistant.restart

        # footer:
        #   type: custom:hui-horizontal-stack-card
        #   cards:
        #     - type: custom:button-card
        #       icon: mdi:restart-alert
        #       name: Reboot System
        #       template: icon_name
        #       tap_action:
        #         action: call-service
        #         service: homeassistant.restart
        #         confirmation:
        #           text: Are you sure you want to restart Home Assistant?
        #       card_mod:
        #         style: |
        #           ha-card {
        #             margin-right: 0.25em;
        #             margin-bottom: 1em;
        #             margin-left: 0.25em;
        #           }

      - type: entities
        view_layout:
          grid-area: tablet
        show_header_toggle: false
        #title: Amazon Fire HD Tablet
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Amazon Fire HD Tablet

          - entity: light.fire_tablet_screen
            name: Display
            icon: hass:tablet

          - type: conditional
            conditions:
              - entity: light.fire_tablet_screen
                state: "on"
            row:
              type: custom:slider-entity-row
              entity: light.fire_tablet_screen
              name: Brightness
              icon: mdi:brightness-6
              hide_state: false

          - type: divider

          - entity: binary_sensor.fire_tablet_plugged_in
            name: Power Supply

          - type: custom:bar-card
            width: 55%
            height: 2em
            decimal: 0
            unit_of_measurement: "%"
            positions:
              icon: outside
              indicator: "off"
              name: outside
            severity:
              - color: "#6d2525"
                from: 0
                to: 25
              - color: "#303435"
                from: 26
                to: 75
              - color: "green"
                from: 76
                to: 100
            entity_row: true
            entities:
              - entity: sensor.custom_fire_tablet_battery_level
                name: Battery Level

          - type: custom:bar-card
            width: 55%
            height: 2em
            decimal: 0
            unit_of_measurement: "%"
            positions:
              icon: outside
              indicator: "off"
              name: outside
            severity:
              - color: "#303435"
                from: 0
                to: 89
              - color: "#6d2525"
                from: 90
                to: 100
            entity_row: true
            entities:
              - entity: sensor.fire_tablet_ram_used_memory
                name: Memory
                icon: hass:memory
              # - entity: sensor.fire_tablet_internal_storage_free_space
              #   icon: hass:database

          - type: divider

          # - entity: button.fire_tablet_reboot_device
          #   icon: mdi:restart
          #   name: Restart Device

          - entity: button.fire_tablet_restart_browser
            icon: mdi:restart
            name: Restart Browser

        # footer:
        #   type: custom:hui-horizontal-stack-card
        #   cards:
        #     - type: custom:button-card
        #       icon: mdi:restart
        #       name: Reboot Device
        #       template: icon_name
        #       tap_action:
        #         action: call-service
        #         service: button.press
        #         target:
        #           entity_id: button.fire_tablet_reboot_device
        #       card_mod:
        #         style: |
        #           ha-card {
        #             margin-right: 0.25em;
        #             margin-bottom: 1em;
        #             margin-left: 0.25em;
        #           }

        #     - type: custom:button-card
        #       icon: mdi:restart
        #       name: Reload Browser
        #       template: icon_name
        #       tap_action:
        #         entity_id: button.fire_tablet_restart_browser
        #         action: call-service
        #         service: button.press
        #         confirmation:
        #           text: Are you sure you want to reload the browser?
        #       card_mod:
        #         style: |
        #           ha-card {
        #             margin-right: 0.25em;
        #             margin-bottom: 1em;
        #             margin-left: 0.25em;
        #           }

        # footer:
        #   cards:
        #     - type: entities
        #       entities:
        #         - entity: button.fire_tablet_reboot_device
        #           icon: mdi:restart
        #           name: Restart Device
        #           template: icon_name

      - type: entities
        view_layout:
          grid-area: network
        show_header_toggle: false
        #title: Network
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Network

          - entity: sensor.network_throughput_in_eth0
            name: Throughput In
          - entity: sensor.network_throughput_out_eth0
            name: Throughput Out
          - type: divider
          # - entity: sensor.unifi_gateway_www_xput_up
          #   name: Unifi, Upload Speed
          # - entity: sensor.unifi_gateway_www_xput_down
          #   name: Unifi, Download Speed
          # - entity: sensor.unifi_gateway_www_speedtest_ping
          #   name: Unifi, Ping
          # - type: divider
          # - entity: sensor.uptime
          #   name: Dream Machine Pro Uptime
          # SpeedTest
          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_upload
            style: |
              :host {
                --paper-item-icon-color: #385581;
              }
          - entity: sensor.speedtest_download
            style: |
              :host {
                --paper-item-icon-color: green;
              }

        footer:
          type: custom:mini-graph-card
          entities:
            - entity: sensor.speedtest_upload
              color: "#385581"
            - entity: sensor.speedtest_download
              color: green
          align_state: left
          group: false
          points_per_hour: 15
          line_width: 3
          hour24: true
          hours_to_show: 1.5
          show:
            {
              fill: fade,
              icon: false,
              name: false,
              state: false,
              name_adaptive_color: true,
              labels: hover,
              legend: false,
            }
          tap_action:
            action: none
