################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Settings
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Settings
  style:
    $: |
      .mdc-dialog .mdc-dialog__content { 
        padding: 0 !important;
      }
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    .: |
      :host .content {
        margin: 0 !important;
        width: calc( 385px * 2 );
        max-width: 90vw;
      }

      @media screen and (max-width: 992px) {
        :host .content {
          width: 100%;
          max-width: none;
        }
      }
    layout-card:
      $grid-layout$:
        .: |
          :host {
            padding: 0;
          }

          #root { 
            margin: -1px !important;
            overflow-x: hidden;
          }

          hui-entities-card { border-left: 1px solid rgba(0, 0, 0, 0.3);}

          @media screen and (max-width: 992px) {
            hui-entities-card { 
              border-top: 1px solid rgba(0, 0, 0, 0.3);
              border-left: 0;
            }
          }

        hui-entities-card:
          $: |
            ha-card {
              padding: 0 !important;
              border-radius: 0;
              margin: 0;
            }

            .card-header,
            .card-content { 
              padding: 1.5em 1.5em !important;
              margin: 0 !important;
            }

            .card-header {
              padding-top: 1em !important;
              padding-bottom: 0 !important;
            }

            @media screen and (max-width: 992px) {
              ha-card { 
                width: 100%;
                width: 100vw;
              }
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(1, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'general notifications'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'general'
            'notifications'
    cards:
      - type: entities
        view_layout:
          grid-area: general
        title: Settings
        show_header_toggle: false
        entities:
          - entity: input_boolean.sync_foyer_lights
            name: Sync Foyer Ceiling Lights
          - entity: input_boolean.vacation_mode
            name: Household Vacation Mode

      - type: entities
        view_layout:
          grid-area: notifications
        title: Notifications
        show_header_toggle: false
        entities:
          - entity: input_boolean.audible_notifications_johan
            name: Household Audible Notifications
          - type: section
            label: Recieve Push Notifications
          - entity: input_boolean.app_notify
            name: All Can Recieve
          - entity: input_boolean.app_notify_tom
            name: Tom Can Recieve
          - entity: input_boolean.app_notify_jess
            name: Jess Can Recieve
