################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Systems
# @description :
#
################################################################################

update_entities:
  action: >
    [[[
      hass.callService( 'homeassistant', 'update_entity', {
          entity_id: [
            'sensor.processor_temperature',
            'sensor.processor_use_percent',
            'sensor.network_throughput_in_eth0',
            'sensor.network_throughput_out_eth0',
            'sensor.speedtest_ping',
            'sensor.speedtest_upload',
            'sensor.speedtest_download'
          ]
      });
    ]]]

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Systems
    #timeout: 15000
    style: >
      --popup-max-width: calc( 385px + 385px );
      --layout-padding: 0;
      --layout-margin: 0;
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              hui-entities-card:
                $: |
                  .card-content {
                    padding: 1.5em 1.5em 0;
                    margin: -2.2em 0 0;
                  }

                  /* Desktop */
                  @media screen and (min-width: 992px) { 
                    .card-content { 
                      border-right: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      border-left: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      margin-right: -1px;
                      margin-left: -1px;
                    }
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 2, 385px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a column_b'
          mediaquery:
            # Tablet and down
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 2, 1fr )
              grid-template-areas: |
                'column_a'
                'column_b'
        cards:
          - type: entities
            view_layout:
              grid-area: column_a
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Home Assistant

              - entity: sensor.processor_temperature
              - type: custom:bar-card
                width: 55%
                height: 2em
                decimal: 0
                unit_of_measurement: "%"
                positions:
                  icon: outside
                  indicator: "off"
                  name: outside
                severity:
                  - color: "#303435"
                    from: 0
                    to: 89
                  - color: "#6d2525"
                    from: 90
                    to: 100
                entity_row: true
                entities:
                  - entity: sensor.processor_use_percent

              - type: divider

              - entity: sensor.home_assistant_log_size
              - entity: sensor.mariadb_database_size
                icon: mdi:database
              #- entity: sensor.influxdb_database_size
              #  icon: mdi:database

              - type: divider

              - entity: input_button.home_assistant_restart
                icon: mdi:restart
                name: Restart System
                tap_action:
                  action: call-service
                  service: homeassistant.restart

          - type: entities
            view_layout:
              grid-area: column_b
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Amazon Fire HD Tablet

              - entity: light.fire_tablet_screen
                name: Display
                icon: hass:tablet

              - type: conditional
                conditions:
                  - entity: light.fire_tablet_screen
                    state: "on"
                row:
                  type: custom:slider-entity-row
                  entity: light.fire_tablet_screen
                  name: Brightness
                  icon: mdi:brightness-6
                  hide_state: false

              - entity: light.tablet_plug
                name: Charger

              - type: divider

              - entity: binary_sensor.fire_tablet_plugged_in
                name: Power Supply

              - type: custom:bar-card
                width: 55%
                height: 2em
                decimal: 0
                unit_of_measurement: "%"
                positions:
                  icon: outside
                  indicator: "off"
                  name: outside
                severity:
                  - color: "#6d2525"
                    from: 0
                    to: 25
                  - color: "#303435"
                    from: 26
                    to: 75
                  - color: "green"
                    from: 76
                    to: 100
                entity_row: true
                entities:
                  - entity: sensor.custom_fire_tablet_battery_level
                    name: Battery Level

              - type: custom:bar-card
                width: 55%
                height: 2em
                decimal: 0
                unit_of_measurement: "%"
                positions:
                  icon: outside
                  indicator: "off"
                  name: outside
                severity:
                  - color: "#303435"
                    from: 0
                    to: 89
                  - color: "#6d2525"
                    from: 90
                    to: 100
                entity_row: true
                entities:
                  - entity: sensor.fire_tablet_ram_used_memory
                    name: Memory
                    icon: hass:memory
                  # - entity: sensor.fire_tablet_internal_storage_free_space
                  #   icon: hass:database

              - type: divider

              # ERROR: Missing root level permissions
              # - entity: button.fire_tablet_reboot_device
              #   icon: mdi:restart
              #   name: Restart Device

              - entity: button.fire_tablet_restart_browser
                icon: mdi:restart
                name: Restart Browser
