################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Household Details
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Household Details
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content {
        overflow-x: hidden;
      }

      /* Desktop */
      @media screen and (min-width: 992px) { 
        :host .content { 
          width: calc(385px + 385px + 385px);
          max-width: 90vw;
        }
      }

    layout-card:
      $grid-layout$:
        .: |
          @media screen and (min-width: 992px) { 
            #root {
              margin-top: 0 !important;
              margin-right: 0 !important;
              margin-left: 0 !important;
            }
          }

        hui-entities-card:
          $: |
            ha-card .card-content { 
              padding-top: 0 !important;
              margin-top: -16px;
            }

            /* Mobile */
            @media screen and (max-width: 992px) { 
              ha-card .card-content { 
                width: 90vw;
              }
            }

            /* Desktop */
            @media screen and (min-width: 992px) { 
              ha-card .card-content { 
                border-right: 1px solid var(--entities-divider-color, var(--divider-color));
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'group_a group_b group_c'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'group_a'
            'group_b'
            'group_c'
    cards:
      - type: entities
        view_layout:
          grid-area: group_a
        show_header_toggle: false
        #title: Column A Title
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Doors

          - entity: lock.front_door
            name: Front Door Lock
          - entity: binary_sensor.door_front_primary
            name: Front Door
          - entity: cover.garage_door
            name: Garage Door (Cover)
          - entity: binary_sensor.door_garage
            name: Garage Door (Interior)
          - entity: binary_sensor.door_living
            name: Living Room Sliding Glass
          - entity: binary_sensor.door_bedroom_1
            name: Main Bedroom
          - entity: binary_sensor.door_bedroom_2
            name: Guest Bedroom
          - entity: binary_sensor.door_bedroom_3
            name: Her Office
          - entity: binary_sensor.door_bedroom_4
            name: His Office
          - entity: binary_sensor.door_laundry
            name: Laundry Room
          #- type: divider
          - entity: sensor.custom_door_closet_hallway_j
            #- entity: binary_sensor.door_closet_hallway_j
            name: Her Closet
          - entity: sensor.custom_door_closet_hallway_t
            #- entity: binary_sensor.door_closet_hallway_t
            name: His Closet

          # - type: section
          #   label: Occupany

          # - entity: binary_sensor.foyer_occupancy
          # - entity: binary_sensor.bedroom_1_occupancy
          # - entity: binary_sensor.bedroom_4_occupancy
          # - entity: binary_sensor.living_room_occupancy

          - type: section
            label: Motion Sensors

          - entity: binary_sensor.foyer_doorbell_motion
            name: Front Door Doorbell
            icon: hass:motion-sensor
          - entity: binary_sensor.motion_laundry
            name: Laundry Room
            icon: hass:motion-sensor

          - type: section
            label: Leak Sensors

          - entity: binary_sensor.leak_air_conditioner
            name: Air Conditioner
          - entity: binary_sensor.leak_washing_machine_laundry
            name: Washing Machine
          - entity: binary_sensor.leak_wine_cooler_bar
            name: Wine Cooler
          - entity: binary_sensor.leak_sink_guest_bathroom
            name: Guest Bathroom, Sink
          - entity: binary_sensor.leak_sink_half_bathroom
            name: Half Bathroom, Sink
          - entity: binary_sensor.leak_sink_kitchen
            name: Kitchen, Sink
          - entity: binary_sensor.leak_sink_main_bathroom_hers
            name: Main Bathroom, Sink (Hers)
          - entity: binary_sensor.leak_sink_main_bathroom_his
            name: Main Bathroom, Sink (His)

      - type: entities
        view_layout:
          grid-area: group_b
        show_header_toggle: false
        #title: Column B Title
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Door Batteries
          - entity: sensor.door_front_primary_battery
            name: Front Door, Primary
          - entity: sensor.door_garage_battery
            name: Garage Door, Interior
          - entity: sensor.door_living_battery
            name: Living Room Sliding Door
          - entity: sensor.door_bedroom_1_battery
            name: Bedroom 1 (Main)
          - entity: sensor.door_bedroom_2_battery
            name: Bedroom 2 (Guest)
          - entity: sensor.door_bedroom_3_battery
            name: Bedroom 3 (Office, Hers)
          - entity: sensor.door_bedroom_4_battery
            name: Bedroom 4 (Office, His)
          - entity: sensor.door_closet_hallway_j_battery
            name: Closet Hallway (Hers)
          - entity: sensor.door_closet_hallway_t_battery
            name: Closet Hallway (His)
          - entity: sensor.door_laundry_battery
            name: Laundry Room

          # - type: conditional
          #   condition:
          #     condition: or
          #     conditions:
          #       - condition: state
          #         entity: sensor.bedroom_1_large_window_left_battery
          #         state_not: "unavailable"
          #       - condition: state
          #         entity: sensor.bedroom_1_large_window_right_battery
          #         state_not: "unavailable"
          #   row:
          #     type: section
          #     label: Curtain Batteries

          # - type: conditional
          #   conditions:
          #     - entity: sensor.bedroom_1_large_window_left_battery
          #       state_not: "unavailable"
          #   row:
          #     entity: sensor.bedroom_1_large_window_left_battery
          #     name: Bedroom 1 Curtain, Large (L)
          # - type: conditional
          #   conditions:
          #     - entity: sensor.bedroom_1_large_window_right_battery
          #       state_not: "unavailable"
          #   row:
          #     entity: sensor.bedroom_1_large_window_right_battery
          #     name: Bedroom 1 Curtain, Large (R)

          - type: section
            label: Water Leak Batteries
          - entity: sensor.leak_air_conditioner_battery
            name: Air Conditioner
          - entity: sensor.leak_sink_kitchen_battery
            name: Kitchen Sink
          - entity: sensor.leak_sink_guest_bathroom_battery
            name: Bathroom Sink (Guest)
          - entity: sensor.leak_sink_half_bathroom_battery
            name: Bathroom Sink (Half)
          - entity: sensor.leak_sink_main_bathroom_hers_battery
            name: Bathroom Sink (Main, Hers)
          - entity: sensor.leak_sink_main_bathroom_his_battery
            name: Bathroom Sink (Main, His)
          - entity: sensor.leak_washing_machine_laundry_battery
            name: Washing Machine
          - entity: sensor.leak_wine_cooler_bar_battery
            name: Wine Cooler (Top)

          - type: section
            label: Temperature Batteries

          - entity: sensor.temp_attic_battery
            name: Attic
          - type: conditional
            conditions:
              - entity: sensor.temp_freezer_battery
                state_not: "unavailable"
            row:
              entity: sensor.temp_freezer_battery
              name: Freezer

          - type: conditional
            conditions:
              - entity: sensor.temp_refrigerator_battery
                state_not: "unavailable"
            row:
              entity: sensor.temp_refrigerator_battery
              name: Refrigerator

          - type: conditional
            conditions:
              - entity: sensor.temp_wine_cooler_top_battery
                state_not: "unavailable"
            row:
              entity: sensor.temp_wine_cooler_top_battery
              name: Wine Cooler (Top)

          - type: conditional
            conditions:
              - entity: sensor.temp_wine_cooler_bottom_battery
                state_not: "unavailable"
            row:
              entity: sensor.temp_wine_cooler_bottom_battery
              name: Wine Cooler (Bottom)

          - type: section
            label: Remote Batteries

          - entity: sensor.switch_bedroom_1_for_bedroom_1_battery
            name: In Bedroom 1, for Bedroom 1
          - entity: sensor.switch_living_room_for_living_room_battery
            name: In Living Room, for Living Room
          - entity: sensor.switch_bedroom_4_for_bedroom_4_battery
            name: In Bedroom 4, for Bedroom 4
          - entity: sensor.switch_kitchen_for_garage_battery
            name: In Kitchen, for Garage
          - entity: sensor.switch_foyer_for_foyer_battery
            name: In Foyer, for Foyer

          - type: section
            label: Motion Sensor Batteries
          - entity: sensor.motion_laundry_battery
            name: Laundry Room

          - type: section
            label: Other Batteries
          - entity: sensor.front_door_battery
            name: Front Door Lock

      - type: entities
        view_layout:
          grid-area: group_c
        show_header_toggle: false
        #title: Column B Title
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Other

          - entity: light.tablet_plug
            name: Kitchen, Tablet Outlet
            icon: mdi:power-socket-us
          - entity: light.bedroom_4_media_plug
            icon: mdi:power-socket-us
            name: His Office, Media Outlet
          - entity: switch.outlet_kitchen_a
            icon: mdi:power-socket-us
            name: Kitchen, Above Range, Outlet
          - entity: switch.outlet_kitchen_b
            icon: mdi:power-socket-us
            name: Kitchen, Above Coffee Bar, Outlet

          - type: section
            label: Television

          - entity: media_player.sony_bravia_tv
            name: Living Room, Television

          - type: section
            label: AppleTV

          - type: conditional
            conditions:
              - entity: media_player.appletv_living_room
                state_not: "unavailable"
              - entity: media_player.appletv_living_room
                state_not: "unknown"
              # - entity: media_player.appletv_living_room
              #   state_not: "standby"
            row:
              entity: media_player.appletv_living_room
              nme: Living Room

          - type: conditional
            conditions:
              - entity: media_player.appletv_bedroom_1
                state_not: "unavailable"
              - entity: media_player.appletv_bedroom_1
                state_not: "unknown"
              # - entity: media_player.appletv_bedroom_1
              #   state_not: "standby"
            row:
              entity: media_player.appletv_bedroom_1
              name: Bedroom (Main)

          - type: conditional
            conditions:
              - entity: media_player.appletv_bedroom_2
                state_not: "unavailable"
              - entity: media_player.appletv_bedroom_2
                state_not: "unknown"
              # - entity: media_player.appletv_bedroom_2
              #   state_not: "standby"
            row:
              entity: media_player.appletv_bedroom_2
              name: Bedroom (Guest)

          - type: conditional
            conditions:
              - entity: media_player.appletv_bedroom_3
                state_not: "unavailable"
              - entity: media_player.appletv_bedroom_3
                state_not: "unknown"
              # - entity: media_player.appletv_bedroom_3
              #   state_not: "standby"
            row:
              entity: media_player.appletv_bedroom_3
              name: Bedroom (Her Office)

          - type: conditional
            conditions:
              - entity: media_player.appletv_bedroom_4
                state_not: "unavailable"
              - entity: media_player.appletv_bedroom_4
                state_not: "unknown"
              # - entity: media_player.appletv_bedroom_4
              #   state_not: "standby"
            row:
              entity: media_player.appletv_bedroom_4
              name: Bedroom (His Office)

          - type: section
            label: Amazon Alexa

          - type: conditional
            conditions:
              - entity: media_player.echo_kitchen
                state_not: "unavailable"
              - entity: media_player.echo_kitchen
                state_not: "unknown"
              # - entity: media_player.echo_kitchen
              #   state_not: "standby"
            row:
              entity: media_player.echo_kitchen
              name: Kitchen

          - type: conditional
            conditions:
              - entity: media_player.echo_dot_dining_room
                state_not: "unavailable"
              - entity: media_player.echo_dot_dining_room
                state_not: "unknown"
              # - entity: media_player.echo_dot_dining_room
              #   state_not: "standby"
            row:
              entity: media_player.echo_dot_dining_room
              name: Dining Room

          - type: conditional
            conditions:
              - entity: media_player.echo_dot_bedroom_1
                state_not: "unavailable"
              - entity: media_player.echo_dot_bedroom_1
                state_not: "unknown"
              # - entity: media_player.echo_dot_bedroom_1
              #   state_not: "standby"
            row:
              entity: media_player.echo_dot_bedroom_1
              name: Bedroom (Main)

          - type: conditional
            conditions:
              - entity: media_player.echo_dot_bedroom_2
                state_not: "unavailable"
              - entity: media_player.echo_dot_bedroom_2
                state_not: "unknown"
              # - entity: media_player.echo_dot_bedroom_2
              #   state_not: "standby"
            row:
              entity: media_player.echo_dot_bedroom_2
              name: Bedroom (Guest)

          - type: conditional
            conditions:
              - entity: media_player.echo_dot_bedroom_3
                state_not: "unavailable"
              - entity: media_player.echo_dot_bedroom_3
                state_not: "unknown"
              # - entity: media_player.echo_dot_bedroom_3
              #   state_not: "standby"
            row:
              entity: media_player.echo_dot_bedroom_3
              name: Bedroom (Her Office)

          - type: conditional
            conditions:
              - entity: media_player.echo_dot_bedroom_4
                state_not: "unavailable"
              - entity: media_player.echo_dot_bedroom_4
                state_not: "unknown"
              # - entity: media_player.echo_dot_bedroom_4
              #   state_not: "standby"
            row:
              entity: media_player.echo_dot_bedroom_4
              name: Bedroom (His Office)
