################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Household Overview
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Household Overview
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content { 
        width: calc(385px + 385px + 385px);
        max-width: 90vw;
      }

      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        :host .content {
          width: 100vw;
          max-width: none;
          overflow-x: hidden;
        }
      }

    layout-card:
      $grid-layout$:
        $: |
          #root {
            margin-right: 0;
            margin-left: 0;
          }
        hui-entities-card:
          $: |
            ha-card { 
              border-radius: 0;
              animation: border 1s forwards;
            }

            @keyframes border {
              0%, 100% {
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

            /* Mobile Devices */
            @media screen and (max-width: 992px) { 
              ha-card {
                width: 100vw;
                animation: none;
              }
            }

          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'group_a group_b group_c'
        'group_a group_b group_d'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'group_a'
            'group_b'
            'group_c'
            'group_d'
    cards:
      - type: entities
        view_layout:
          grid-area: group_a
        #title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Common Areas

          - entity: light.kitchen_ceiling_lights
            name: Kitchen, Ceiling
            secondary_info: brightness
          - entity: light.dining_room_chandelier
            name: Dining Room, Chandelier
            icon: bha:chandelier
            secondary_info: brightness
          - entity: light.living_room_corner_lamp
            name: Living Room, Corner
            icon: bha:table-lamp-variant
            secondary_info: brightness

          - entity: light.foyer_hallway_ceiling
            name: Foyer, Hallway
            secondary_info: brightness
          - entity: light.foyer_entryway_ceiling
            name: Foyer, Entryway
            secondary_info: brightness
          - entity: light.foyer_ceiling_ledge
            name: Foyer, Ledge
            secondary_info: brightness
          - entity: light.foyer_under_table
            name: Foyer, Under Table
            secondary_info: brightness

      - type: entities
        view_layout:
          grid-area: group_b
        #title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Bedrooms, Offices, and Other

          - entity: light.bedroom_1_bedside_lamps
            name: Main Bedroom, Bedside
            secondary_info: brightness
          - entity: light.closet_hallway_ceiling_light
            name: Closet Hallway, Ceiling
            icon: bha:dome-light
            secondary_info: brightness
          - entity: light.closet_hallway_light_j
            name: Closet, Ceiling (Hers)
            secondary_info: brightness
          - entity: light.closet_hallway_light_t
            name: Closet, Ceiling (His)
            secondary_info: brightness
          - entity: light.bedroom_4_desk_lamp
            name: His Office, Desk Lamp
            secondary_info: brightness
          - entity: light.bedroom_4_lightstrip
            name: His Office, Lightstrip
            secondary_info: brightness
          - entity: light.laundry_ceiling_light
            name: Laundry Room, Ceiling
            icon: bha:dome-light
            secondary_info: brightness

      - type: entities
        view_layout:
          grid-area: group_c
        #title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Lights, Exterior

          - entity: light.foyer_exterior_entryway
            name: Front Door Entry
            icon: hass:globe-light
            secondary_info: brightness
          - entity: light.garage_exterior
            name: Garage Exterior
            icon: bha:outdoor-lamp-variant
            secondary_info: brightness
          - entity: switch.backyard_string_lights
            name: Backyard String Lights
            icon: bha:light-string

      - type: entities
        view_layout:
          grid-area: group_d
        #title: Home Assistant
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Exterior Doors

          - entity: lock.front_door
            name: Front Door
          - entity: cover.garage_door
            name: Garage Door
          - entity: binary_sensor.door_living
            name: Living Room Sliding Glass
