################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Settings
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Settings
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content { 
        width: calc(385px + 385px + 385px);
        max-width: 90vw;
      }

      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        :host .content {
          width: 100vw;
          max-width: none;
          overflow-x: hidden;
        }
      }

    layout-card:
      $grid-layout$:
        $: |
          #root {
            margin-right: 0;
            margin-left: 0;
          }
        hui-entities-card:
          $: |
            ha-card { 
              border-radius: 0;
              animation: border 1s forwards;
            }

            @keyframes border {
              0%, 100% {
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

            /* Mobile Devices */
            @media screen and (max-width: 992px) { 
              ha-card {
                width: 100vw;
                animation: none;
              }
            }

          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b column_c'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_c'
            'column_b'
    cards:
      - type: entities
        view_layout:
          grid-area: column_a
        show_header_toggle: false
        title: Status
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Waste Collection

          - type: conditional
            conditions:
              - entity: sensor.waste_day_solid
                state_not: "Never"
            row:
              entity: sensor.waste_day_solid
              name: Solid Waste

          - type: conditional
            conditions:
              - entity: sensor.waste_day_bulk
                state_not: "Never"
            row:
              entity: sensor.waste_day_bulk
              name: Bulk Waste

          - type: conditional
            conditions:
              - entity: sensor.waste_day_recycling
                state_not: "Never"
            row:
              entity: sensor.waste_day_recycling
              name: Recycling

          - type: section
            label: Clean Household
          - entity: sensor.cleaning_day
            name: Frances Comes

          - type: section
            label: Automation Status
          - entity: sensor.automation_daily_status
            name: Daily, In Evening
          - entity: input_boolean.home_away_mode
            name: Home Away Mode

          - type: conditional
            conditions:
              - entity: input_boolean.manual_override_foyer_exterior_entryway
                state: "on"
            row:
              entity: input_boolean.manual_override_foyer_exterior_entryway
              name: Foyer Exterior, Override

          - type: conditional
            conditions:
              - entity: timer.doorbell_motion_snooze
                state_not: "idle"
            row:
              entity: timer.doorbell_motion_snooze
              name: Doorbell Snoozed

          # - type: conditional
          #   conditions:
          #     - entity: timer.doorbell_motion_snooze
          #       state_not: "idle"
          #   row:
          #     entity: timer.doorbell_motion_snooze
          #     name: Doorbell Snoozed

          - type: conditional
            conditions:
              - entity: timer.doorbell_motion_snooze
                state: "active"
            row:
              entity: sensor.doorbell_motion_snooze_countdown
              name: Doorbell Snoozed Until

          - type: conditional
            conditions:
              - entity: input_boolean.doorbell_motion_snooze_today
                state_not: "off"
            row:
              entity: input_boolean.doorbell_motion_snooze_today
              name: Doorbell Snoozed, Today

          - type: conditional
            conditions:
              - entity: input_boolean.doorbell_motion_snooze_indefinite
                state_not: "off"
            row:
              entity: input_boolean.doorbell_motion_snooze_indefinite
              name: Doorbell Snoozed, Indefinite

      - type: entities
        view_layout:
          grid-area: column_b
        show_header_toggle: false
        title: Notifications
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: House Notifications
          - entity: input_boolean.household_notify
            name: Alexa Announcements

          - type: section
            label: Mobile Notifications
          - entity: input_boolean.app_notify
            name: All Devices Can Recieve
          - entity: input_boolean.app_notify_tom
            name: His Phone Can Recieve
          - entity: input_boolean.app_notify_jess
            name: Her Phone Can Recieve

      - type: entities
        view_layout:
          grid-area: column_c
        title: Sync Lights
        show_header_toggle: false
        entities:
          - entity: input_boolean.sync_foyer_lights
            name: Foyer, Entryway & Hallway
