################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Temperature
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Temperature
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content { 
        width: calc(385px + 385px + 385px);
        max-width: 90vw;
      }

      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        :host .content {
          width: 100vw;
          max-width: none;
          overflow-x: hidden;
        }
      }

    layout-card:
      $grid-layout$:
        $: |
          #root {
            margin-right: 0;
            margin-left: 0;
          }
        hui-thermostat-card:
          $: |
            ha-card { 
              border-radius: 0;
              width: 350px;
            }

        hui-entities-card:
          $: |
            ha-card { 
              border-radius: 0;
              animation: border 1s forwards;
            }

            @keyframes border {
              0%, 100% {
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

            /* Mobile Devices */
            @media screen and (max-width: 992px) { 
              ha-card {
                width: 100vw;
                animation: none;
              }
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b column_c'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
            'column_c'

    cards:
      - type: thermostat
        entity: climate.ecobee
        view_layout:
          grid-area: column_a
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}

      - type: entities
        view_layout:
          grid-area: column_b
        show_header_toggle: false
        title: Rooms
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - entity: sensor.foyer_temperature
            name: Foyer

          - entity: sensor.living_room_temperature
            name: Living Room

          - entity: sensor.bedroom_1_temperature
            name: Main Bedroom

          - entity: sensor.bedroom_4_temperature
            name: His Office

          - type: conditional
            conditions:
              - entity: sensor.temp_attic_temperature
                state_not: "unavailable"
            row:
              entity: sensor.temp_attic_temperature
              name: Attic

      - type: entities
        view_layout:
          grid-area: column_c
        show_header_toggle: false
        title: Appliances
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: conditional
            conditions:
              - entity: sensor.temp_freezer_temperature
                state_not: "unavailable"
            row:
              entity: sensor.temp_freezer_temperature
              name: Freezer
            style: |
              :host {
                --paper-item-icon-color: #7c4dff;
              }

          - type: conditional
            conditions:
              - entity: sensor.temp_refrigerator_temperature
                state_not: "unavailable"
            row:
              entity: sensor.temp_refrigerator_temperature
              name: Refrigerator

          - type: conditional
            conditions:
              - entity: sensor.temp_wine_cooler_temperature
                state_not: "unavailable"
            row:
              entity: sensor.temp_wine_cooler_temperature
              name: Wine Cooler

          # - type: divider

          # - entity: sensor.foyer_humidity
          #   name: Humidity
