################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Settings
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Settings
  large: false
  style:
    $: |
      /* Mobile Devices */
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }

    .: |
      :host .content {
        overflow-x: hidden;
      }

      /* Desktop */
      @media screen and (min-width: 992px) { 
        :host .content { 
          width: calc(385px + 385px);
          max-width: 90vw;
        }
      }

    layout-card:
      $grid-layout$:
        .: |
          @media screen and (min-width: 992px) { 
            #root {
              margin-top: 0 !important;
              margin-right: 0 !important;
              margin-left: 0 !important;
            }
          }

        hui-entities-card:
          $: |
            ha-card .card-content { 
              padding-top: 0 !important;
              margin-top: -16px;
            }

            /* Mobile */
            @media screen and (max-width: 992px) { 
              ha-card .card-content { 
                width: 90vw;
              }
            }

            /* Desktop */
            @media screen and (min-width: 992px) { 
              ha-card .card-content { 
                border-right: 1px solid var(--entities-divider-color, var(--divider-color));
                border-left: 1px solid var(--entities-divider-color, var(--divider-color));
              }
            }

          $hui-horizontal-stack-card$: |
            #root {
              justify-content: space-evenly;
              margin-top: 1.9em;
              margin-left: 0.8em;
            }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(2, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        'column_a column_b'
      mediaquery:
        # Tablet and down
        "(max-width: 992px)":
          grid-template-columns: 1fr
          grid-template-rows: repeat(1, 1fr)
          grid-template-areas: |
            'column_a'
            'column_b'
    cards:
      - type: entities
        view_layout:
          grid-area: column_a
        show_header_toggle: false
        #title: Status
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Waste Collection

          - type: conditional
            conditions:
              - entity: sensor.waste_day_solid
                state_not: "Never"
            row:
              entity: sensor.waste_day_solid
              name: Solid Waste

          - type: conditional
            conditions:
              - entity: sensor.waste_day_bulk
                state_not: "Never"
            row:
              entity: sensor.waste_day_bulk
              name: Bulk Waste

          - type: conditional
            conditions:
              - entity: sensor.waste_day_recycling
                state_not: "Never"
            row:
              entity: sensor.waste_day_recycling
              name: Recycling

          - type: section
            label: Clean Household
          - entity: sensor.cleaning_day
            name: Frances Comes

      - type: entities
        view_layout:
          grid-area: column_b
        show_header_toggle: false
        #title: Notifications
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0 !important;
              width: 100%;
            }
            .name { margin: 0 0 1em !important;}
        entities:
          - type: section
            label: Sync Lights

          - type: conditional
            conditions:
              - entity: light.bedroom_1_lamp_j
                state_not: "unavailable"
              - entity: light.bedroom_1_lamp_t
                state_not: "unavailable"
            row:
              entity: input_boolean.sync_bedroom_1_bedside_lamps
              name: Main Bedroom, Bedside Lamps

          - type: conditional
            conditions:
              - entity: light.foyer_ceiling_lights
                state_not: "unavailable"
            row:
              entity: input_boolean.sync_foyer_lights
              name: Foyer, Entryway & Hallway

          - type: conditional
            conditions:
              - entity: light.bedroom_4_lights
                state_not: "unavailable"
            row:
              entity: input_boolean.sync_bedroom_4_lights
              name: Tom's Office

          - type: section
            label: Notifications
          - entity: input_boolean.household_notify
            name: Alexa Announcements
          - entity: input_boolean.app_notify
            name: Mobile Push Notifications
