################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Person (UDMP)
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: UniFi Dream Machine
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
    hui-vertical-stack-card:
      $: |
        hui-horizontal-stack-card {
          padding: 0em 2em 2.3em 2em;
        }
  card:
    type: vertical-stack
    cards:
      - type: entities
        state_color: true
        card_mod:
          class: content
        entities:

          #- entity: binary_sensor.template_udm_internet
          #  secondary_info: last-changed

          - entity: sensor.casamaxson_udmp_cpu_temperature
            name: CPU Temperature

          - type: custom:bar-card
            width: 55%
            height: 2em
            decimal: 0
            unit_of_measurement: '%'
            positions:
              icon: outside
              indicator: 'off'
              name: outside
            severity:
              - color: '#6d2525'
                from: 90
                to: 999
            entity_row: true
            entities:
              - entity: sensor.casamaxson_udmp_cpu_utilization
                name: CPU Utilization
              - entity: sensor.casamaxson_udmp_memory_utilization
                name: Memory Utilization
              - entity: sensor.casamaxson_udmp_storage_utilization
                name: Storage Utilization

          - entity: sensor.casamaxson_udmp_uptime
            name: Uptime
          #- entity: binary_sensor.template_udm_upgradable

          - type: divider

          - entity: sensor.speedtest_ping
          - entity: sensor.speedtest_upload
            style: |
              :host {
                --paper-item-icon-color: #385581;
              }
          - entity: sensor.speedtest_download
            style: |
              :host {
                --paper-item-icon-color: green;
              }

        footer:
          type: custom:mini-graph-card
          entities:
            - entity: sensor.speedtest_upload
              color: "#385581"
            - entity: sensor.speedtest_download
              color: green
          align_state: left
          group: false
          points_per_hour: 15
          line_width: 3
          hour24: true
          hours_to_show: 1.5
          show:
            {
              fill: fade,
              icon: false,
              name: false,
              state: false,
              name_adaptive_color: true,
              labels: hover,
              legend: false,
            }
          tap_action:
            action: none