################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Sidebar Controls
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  title: Sidebar
  style:
    $: |
      @media screen and (max-width: 992px) { 
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface { 
          border-radius: 0 !important;
        }
      }
  card:
    type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: input_boolean.sidebar_display_holidays
            name: Upcoming Holidays
          - entity: input_boolean.sidebar_display_celebrations
            name: Upcoming Celebrations
          - entity: input_boolean.sidebar_display_neighborhood
            name: Display Neighborhood Events
          - entity: input_boolean.sidebar_display_weather_forecast
            name: Weather Forecast
          - entity: input_boolean.sidebar_display_lights_on
            name: Total Lights On
          - entity: input_boolean.sidebar_display_doors_open
            name: Total Doors Open
          - entity: input_boolean.sidebar_display_exterior_door_status
            name: Exterior Door Status
          - entity: input_boolean.sidebar_display_sunrise_sunset
            name: Next Sunrise/Sunset
          - type: divider
          - entity: input_boolean.sidebar_display_waste_reminder
            name: Waste Reminders
