################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Temperature
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Temperatures
    # timeout: 15000
    style: >
      --popup-max-width: calc( 385px + 385px + 385px );
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              .: |
                #root { overflow: hidden;}

              hui-thermostat-card:
                $: |
                  .type-thermostat { 
                    border-top: 1px solid var( --entities-divider-color, var( --divider-color ) );
                    margin: 1px 6px 0 !important;
                  }

              hui-entities-card:
                $: |
                  .card-content { 
                    padding: 1.5em 1.5em 0;
                    margin: -2em 0 1em;
                  }

                  /* Desktop */
                  @media screen and (min-width: 992px) { 
                    .card-content { 
                      border-right: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      border-left: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      margin-right: -1px;
                      margin-left: -1px;
                    }
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 3, 385px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a column_b column_c'
          mediaquery:
            # Tablet and down
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 3, 1fr )
              grid-template-areas: |
                'column_a'
                'column_b'
                'column_c'
        cards:
          - type: thermostat
            entity: climate.ecobee
            view_layout:
              grid-area: column_a
            show_header_toggle: false
            card_mod:
              class: column

          - type: entities
            view_layout:
              grid-area: column_b
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Rooms

              - entity: sensor.foyer_temperature
                name: Foyer

              - entity: sensor.living_room_temperature
                name: Living Room

              - entity: sensor.bedroom_1_temperature
                name: Main Bedroom

              - entity: sensor.bedroom_2_temperature
                name: Guest Bedroom

              - entity: sensor.bedroom_3_temperature
                name: Her Office

              - entity: sensor.bedroom_4_temperature
                name: His Office

          - type: entities
            view_layout:
              grid-area: column_c
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Areas

              - entity: sensor.temp_attic_temperature
                name: Attic

              - type: section
                label: Appliances

              - entity: sensor.temp_freezer_temperature
                name: Freezer

              - entity: sensor.temp_refrigerator_temperature
                name: Refrigerator

              - entity: sensor.temp_wine_cooler_top_temperature
                name: Wine Cooler, Upper

              - entity: sensor.temp_wine_cooler_bottom_temperature
                name: Wine Cooler, Lower
