################################################################################
#
# @author      : Thomas Maxson
# @package     : Popup, Household Details
# @description :
#
################################################################################

action: fire-dom-event
browser_mod:
  command: popup
  service: browser_mod.popup
  data:
    title: Household Details
    #timeout: 15000
    style: >
      --popup-max-width: calc( 385px + 385px + 385px );
    content:
      type: custom:mod-card
      card_mod:
        style:
          layout-card$:
            grid-layout$:
              .: |
                #root { overflow: hidden;}
              hui-entities-card:
                $: |
                  .card-content {
                    padding: 1.5em 1.5em 0;
                    margin: -2em 0 1em;
                  }

                  /* Desktop */
                  @media screen and (min-width: 992px) { 
                    .card-content { 
                      border-right: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      border-left: 1px solid var( --entities-divider-color, var( --divider-color ) );
                      margin-right: -1px;
                      margin-left: -1px;
                      overflow: hidden;
                    }
                  }
      card:
        type: custom:layout-card
        layout_type: custom:grid-layout
        layout:
          margin: 0
          grid-template-columns: repeat( 3, 385px )
          grid-template-rows: 1fr
          grid-template-areas: |
            'column_a column_b column_c'
          mediaquery:
            "(max-width: 992px)":
              grid-template-columns: 1fr
              grid-template-rows: repeat( 3, 1fr )
              grid-template-areas: |
                'column_a'
                'column_b'
                'column_c'
        cards:
          - type: entities
            view_layout:
              grid-area: column_a
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Doors

              - type: custom:mushroom-cover-card
                entity: cover.garage_door
                name: Garage Door (Cover)
                show_buttons_control: true
                show_position_control: true

              - type: custom:mushroom-lock-card
                entity: lock.front_door
                name: Front Door Lock
                layout: horizontal

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_front_primary
                  - battery: sensor.door_front_primary_battery
                  - name: Front Door (Primary)

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_front_secondary
                  - battery: sensor.door_front_secondary_battery
                  - name: Front Door (Secondary)

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_garage
                  - battery: sensor.door_garage_battery
                  - name: Garage Door (Interior)

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_living
                  - battery: sensor.door_living_battery
                  - name: Living Room Sliding Glass Door

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_bedroom_1
                  - battery: sensor.door_bedroom_1_battery
                  - name: Main Bedroom Door

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_bedroom_2
                  - battery: sensor.door_bedroom_2_battery
                  - name: Guest Bedroom Door

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_bedroom_3
                  - battery: sensor.door_bedroom_3_battery
                  - name: Office Door (Hers)

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_bedroom_4
                  - battery: sensor.door_bedroom_4_battery
                  - name: Office Door (His)

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_laundry
                  - battery: sensor.door_laundry_battery
                  - name: Laundry Room Door

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_closet_hallway_hers
                  - battery: sensor.door_closet_hallway_his_battery
                  - name: Closet Door (Hers)
                  - icon_open: door-sliding-open
                  - icon_closed: door-sliding

              - type: custom:decluttering-card
                template: entity_door_details
                variables:
                  - entity: binary_sensor.door_closet_hallway_his
                  - battery: sensor.door_closet_hallway_his_battery
                  - name: Closet Door (His)
                  - icon_open: door-sliding-open
                  - icon_closed: door-sliding

              # - type: section
              #   label: Occupany

              # - entity: binary_sensor.foyer_occupancy
              # - entity: binary_sensor.bedroom_1_occupancy
              # - entity: binary_sensor.bedroom_4_occupancy
              # - entity: binary_sensor.living_room_occupancy

          - type: entities
            view_layout:
              grid-area: column_b
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Power Outlets

              - type: custom:decluttering-card
                template: entity_power_outlet
                variables:
                  - entity: light.tablet_plug
                  - name: Kitchen, Tablet

              - type: custom:decluttering-card
                template: entity_power_outlet
                variables:
                  - entity: switch.outlet_kitchen_a
                  - name: Kitchen, Above Range

              - type: custom:decluttering-card
                template: entity_power_outlet
                variables:
                  - entity: switch.outlet_kitchen_b
                  - name: Kitchen, Above Coffee Bar

              - type: custom:decluttering-card
                template: entity_power_outlet
                variables:
                  - entity: light.bedroom_4_media_plug
                  - name: His Office, Media

              # - type: custom:decluttering-card
              #   template: entity_power_outlet
              #   variables:
              #     - entity: light.garage_fan
              #     - name: Garage, Fan

              - type: section
                label: Presence

              - type: custom:mushroom-entity-card
                entity: binary_sensor.presence_living_room
                name: Living Room
                icon: hass:motion-sensor

              - type: section
                label: Motion Sensors

              - type: custom:mushroom-entity-card
                entity: binary_sensor.foyer_doorbell_motion
                name: Front Door Doorbell
                icon: hass:motion-sensor

              - type: custom:mushroom-entity-card
                entity: binary_sensor.motion_laundry
                name: Laundry Room
                icon: hass:motion-sensor

              - type: section
                label: Leak Sensors

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_air_conditioner
                  - battery: sensor.leak_air_conditioner_battery
                  - name: Air Conditioner

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_sink_guest_bathroom
                  - battery: sensor.leak_sink_guest_bathroom_battery
                  - name: Sink, Bathroom (Guest)

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_sink_half_bathroom
                  - battery: sensor.leak_sink_half_bathroom_battery
                  - name: Sink, Bathroom (Half)

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_sink_main_bathroom_hers
                  - battery: sensor.leak_sink_main_bathroom_hers_battery
                  - name: Sink, Bathroom (Main, Hers)

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_sink_main_bathroom_his
                  - battery: sensor.leak_sink_main_bathroom_his_battery
                  - name: Sink, Bathroom (Main, His)

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_sink_kitchen
                  - battery: sensor.leak_sink_kitchen_battery
                  - name: Sink, Kitchen

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_wine_cooler_bar
                  - battery: sensor.leak_wine_cooler_bar_battery
                  - name: Wine Cooler

              - type: custom:decluttering-card
                template: entity_leak_details
                variables:
                  - entity: binary_sensor.leak_washing_machine_laundry
                  - battery: sensor.leak_washing_machine_laundry_battery
                  - name: Washing Machine

          - type: entities
            view_layout:
              grid-area: column_c
            show_header_toggle: false
            card_mod:
              class: column
            entities:
              - type: section
                label: Lock Batteries

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: lock.front_door
                  - battery: sensor.front_door_battery
                  - name: Front Door Lock

              - type: section
                label: Temperature Batteries

              - type: conditional
                conditions:
                  - entity: sensor.temp_attic_temperature
                    state_not: "unavailable"
                row:
                  type: custom:decluttering-card
                  template: entity_battery_level
                  variables:
                    - entity: sensor.temp_attic_temperature
                    - battery: sensor.temp_attic_battery
                    - name: Attic

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.temp_freezer_temperature
                  - battery: sensor.temp_freezer_battery
                  - name: Freezer

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.temp_refrigerator_temperature
                  - battery: sensor.temp_refrigerator_battery
                  - name: Refrigerator

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.temp_wine_cooler_top_temperature
                  - battery: sensor.temp_wine_cooler_top_battery
                  - name: Wine Cooler (Top)

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.temp_wine_cooler_bottom_temperature
                  - battery: sensor.temp_wine_cooler_bottom_battery
                  - name: Wine Cooler (Bottom)

              - type: section
                label: Motion Sensor Batteries

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: binary_sensor.motion_laundry
                  - battery: sensor.motion_laundry_battery
                  - name: Laundry Room

              - type: section
                label: Remote Batteries

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.remote_garage_for_garage_fan_battery
                  - battery: sensor.remote_garage_for_garage_fan_battery
                  - name: In Garage, for Garage Fan

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.remote_living_room_for_living_room_battery
                  - battery: sensor.remote_living_room_for_living_room_battery
                  - name: In Living Room, for Living Room Lights

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.remote_bedroom_4_for_bedroom_4_battery
                  - battery: sensor.remote_bedroom_4_for_bedroom_4_battery
                  - name: In Bedroom 4, for Bedroom 4 Lights

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.remote_kitchen_for_garage_battery
                  - battery: sensor.remote_kitchen_for_garage_battery
                  - name: In Kitchen, for Garage Door

              - type: custom:decluttering-card
                template: entity_battery_level
                variables:
                  - entity: sensor.remote_foyer_for_foyer_battery
                  - battery: sensor.remote_foyer_for_foyer_battery
                  - name: In Foyer, for Foyer Lights
