- id: '1632277288633'
  alias: 'Set Default: Theme on Load'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: Custom Dashboard
  mode: single
