- id: '1632277288633'
  alias: 'Set Default: Theme on Load'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: tihiti
  mode: single
- id: '1651337763691'
  alias: Remove Snapshots, Older than 7 Days
  description: ''
  trigger:
  - platform: time
    at: 02:30:00
  condition: []
  action:
  - service: delete.files_in_folder
    data:
      folder: /config/www/snapshots/
      time: 604800
  mode: single
