################################################################################
#
# @author      : Thomas Maxson
# @package     : Themes
# @description :
#
################################################################################

extra_module_url:
  - /hacsfiles/hass-bha-icons/hass-bha-icons.js
  - /hacsfiles/hass-hue-icons/hass-hue-icons.js

themes:
  Tihiti:
    primary-text-color: "#e1e1e1"
    primary-background-color: "#111111"
    secondary-background-color: "#202020"
    card-background-color: "#1c1c1c"
    primary-color: "#03a9f4"
    app-header-text-color: var(--primary-text-color)
    app-header-background-color: "#101e24"
    table-row-background-color: var(--primary-background-color)
    table-row-alternative-background-color: var(--secondary-background-color)
    sidebar-background-color: var(--card-background-color)
    divider-color: rgba(225, 225, 225, 0.12)
    input-idle-line-color: rgba(255, 255, 255, 0.42)
    input-hover-line-color: rgba(255, 255, 255, 0.87)
    input-disabled-line-color: rgba(255, 255, 255, 0.06)
    input-outlined-idle-border-color: rgba(255, 255, 255, 0.38)
    input-outlined-hover-border-color: rgba(255, 255, 255, 0.87)
    input-outlined-disabled-border-color: rgba(255, 255, 255, 0.06)
    input-fill-color: rgba(255, 255, 255, 0.05)
    input-disabled-fill-color: rgba(255, 255, 255, 0.02)
    input-ink-color: rgba(255, 255, 255, 0.87)
    input-label-ink-color: rgba(255, 255, 255, 0.6)
    input-disabled-ink-color: rgba(255, 255, 255, 0.37)
    input-dropdown-icon-color: rgba(255, 255, 255, 0.54)

    # Edited
    ha-card-box-shadow: none
    ha-card-background: none
    grid-card-gap: 5%
    masonry-view-card-margin: 0

    state-icon-color: "#9da0a2"
    state-icon-active-color: "#3182b7"

    switch-unchecked-button-color: "#3b4041"
    switch-unchecked-track-color: "#0c0d0d"

    # paper-slider-knob-color: "#a4abb1"
    # paper-slider-knob-start-color: "#a4abb1"
    # paper-slider-pin-color: "#626a6f"
    # paper-slider-active-color: '#626a6f'
    # paper-slider-container-color: "#202020"
    # paper-toast-color: var( --primary-text-color )
    # paper-toast-background-color: "#1b1b1bf2"

    # Font
    primary-font-family: SF Pro Text, SF Text, Roboto, system-ui
    paper-font-common-base_-_font-family: var(--primary-font-family)
    paper-font-common-code_-_font-family: var(--primary-font-family)
    paper-font-body1_-_font-family: var(--primary-font-family)
    paper-font-subhead_-_font-family: var(--primary-font-family)
    paper-font-headline_-_font-family: var(--primary-font-family)
    paper-font-caption_-_font-family: var(--primary-font-family)
    paper-font-title_-_font-family: var(--primary-font-family)
    ha-card-header-font-family: var(--primary-font-family)
    mdc-typography-body1-font-family: var(--primary-font-family)
    mdc-typography-font-family: var(--primary-font-family)

    # Custom Variables
    ha-card-background-color: rgba(34,38,39,0.9)
    ha-card-header-background-color: rgba(48,52,52,0.8)
    card-content-padding: 1.4em 2.2em 1.6em 1.5em

    bar-card-color: "#303435"

    # Button Card Templates
    button-card-font-size: 1.35vw
    button-card-font-weight: 500
    button-card-letter-spacing: -0.03vw
    button-card-border-radius: 10px

    # Popups
    mdc-dialog-scrim-color: rgba( 0, 0, 0, 0.5 )
    dialog-backdrop-filter: blur( 2em ) brightness( 0.75 )
    ## browser_mod.popup
    popup-background-color: var( --card-background-color )
    popup-padding-x: 0
    popup-padding-y: 0
    popup-border-width: 1px
    popup-border-radius: 0

    #
    # Tihiti
    # --------------------------------------------------

    # Generic
    tihiti-dashboard-layout-padding: 3.3vw

    # Sidebar
    tihiti-sidebar-time-font-size: 5vw
    tihiti-sidebar-font-size: 1.5vw
    tihiti-sidebar-line-height: 2vw

    # Footer
    tihiti-footer-card-font-size: 1.2rem
    tihiti-footer-card-icon-size: 1.8rem
    tihiti-footer-card-padding-v: 1vw
    tihiti-footer-card-padding-h: 1.25vw
    tihiti-footer-card-border-radius: 10px

    # Popups
    #tihiti-popup-header-color: rgba( 200, 218, 222, 0.05 )
    tihiti-popup-header-color: rgba( 255, 0, 0, 0.5 )
    # tihiti-popup-button-padding: 0.1em 2em 1.8em 2em
    # tihiti-popup-border-style: 1.5px solid rgba( 0, 0, 0, 0.2 )

    ####################################################
    #                                                  #
    #                     CARD-MOD                     #
    #                                                  #
    ####################################################

    card-mod-theme: tihiti

    card-mod-root: |
      ha-app-layout { 
        background: none !important;
        min-height: 100vh;
      }

    card-mod-view-yaml: |
      .: |
        hui-view { 
          background: none !important;
          min-height: 100vh;
        }
