################################################################################
#
# @author      : Thomas Maxson
# @package     : Button, Media (AppleTV)
# @description :
#
################################################################################

card:
  type: custom:button-card
  entity: "[[entity]]"
  name: "[[name]]"
  template:
    - media
  double_tap_action:
    action: fire-dom-event
    browser_mod:
      command: popup
      service: browser_mod.popup
      data:
        title: >
          [[[
            return ! entity || entity.attributes.friendly_name
          ]]]
        style: >
          --popup-max-width: calc( 385px );
          --ha-card-border-radius: 0;
        content:
          type: custom:layout-card
          layout_type: grid
          layout:
            margin: 30px 0 30px 35px
            grid-template-rows: auto
            grid-template-columns: 30% 30% 30%
          cards:
            - type: custom:gap-card
            - type: custom:button-card
              aspect_ratio: 1/1
              icon: mdi:power
              name: Power
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command:
                    - home_hold
                    - select
                  entity_id: "[[remote]]"
              styles:
                icon:
                  - color: >
                      [[[
                        if (entity.state == 'playing') return 'red';
                        else return 'white';
                      ]]]
            - type: custom:gap-card
            - type: custom:button-card
              aspect_ratio: 1/1
              icon: mdi:play-pause
              name: Play/Pause
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: play_pause
                  entity_id: "[[remote]]"
            # - type: custom:button-card
            #   icon: mdi:skip-backward
            #   name: Down
            #   show_icon: true
            #   show_name: false
            #   tap_action:
            #     action: call-service
            #     service: remote.send_command
            #     service_data:
            #       command: skip_backward
            #       entity_id: "[[remote]]"
            # - type: custom:button-card
            #   icon: mdi:skip-forward
            #   name: Down
            #   show_icon: true
            #   show_name: false
            #   tap_action:
            #     action: call-service
            #     service: remote.send_command
            #     service_data:
            #       command: skip_forward
            #       entity_id: "[[remote]]"
            - type: custom:button-card
              aspect_ratio: 1/1
              name: MENU
              show_icon: false
              show_name: true
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: home
                  entity_id: "[[remote]]"
            - type: custom:button-card
              aspect_ratio: 1/1
              icon: mdi:television
              name: AppleTV
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: menu
                  entity_id: "[[remote]]"

            - type: custom:gap-card
            - type: custom:button-card
              aspect_ratio: 1/1
              size: 75px
              icon: mdi:chevron-up
              name: Up
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: up
                  entity_id: "[[remote]]"
            - type: custom:gap-card

            - type: custom:button-card
              aspect_ratio: 1/1
              size: 75px
              icon: mdi:chevron-left
              name: Left
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: left
                  entity_id: "[[remote]]"
            - type: custom:button-card
              aspect_ratio: 1/1
              size: 75px
              icon: mdi:circle-outline
              name: Select
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: select
                  entity_id: "[[remote]]"
            - type: custom:button-card
              aspect_ratio: 1/1
              size: 75px
              icon: mdi:chevron-right
              name: Right
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: right
                  entity_id: "[[remote]]"

            - type: custom:gap-card
            - type: custom:button-card
              aspect_ratio: 1/1
              size: 75px
              icon: mdi:chevron-down
              name: Down
              show_icon: true
              show_name: false
              tap_action:
                action: call-service
                service: remote.send_command
                service_data:
                  command: down
                  entity_id: "[[remote]]"
            - type: custom:gap-card

            # - type: custom:button-card
            #   aspect_ratio: 1/1
            #   icon: mdi:volume-plus
            #   name: Volume Up
            #   show_icon: true
            #   show_name: false
            #   tap_action:
            #     action: call-service
            #     service: remote.send_command
            #     service_data:
            #       command: volume_up
            #       entity_id: "[[remote]]"
            # - type: custom:button-card
            #   aspect_ratio: 1/1
            #   icon: mdi:volume-minus
            #   name: Volume Down
            #   show_icon: true
            #   show_name: false
            #   tap_action:
            #     action: call-service
            #     service: remote.send_command
            #     service_data:
            #       command: volume_down
            #       entity_id: "[[remote]]"
            # - type: custom:button-card
            #   aspect_ratio: 1/1
            #   icon: mdi:volume-mute
            #   name: Mute
            #   show_icon: true
            #   show_name: false
            #   tap_action:
            #     action: call-service
            #     service: remote.send_command
            #     service_data:
            #       command: volume_mute
            #       entity_id: "[[remote]]"
