################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Battery Level
# @description :
#
################################################################################

card:
  type: custom:mushroom-template-card
  primary: '[[name]]'
  secondary: "{{ states('[[entity]]') }}%"
  icon: |+
    {% set battery_level = ( states( '[[entity]]' ) | int / 10 ) | round(0) | int * 10 %}
    {% if battery_level == 100 %}
      mdi:battery
    {% elif battery_level > 20 %}
      mdi:battery-{{ battery_level }}
    {% else %}
      mdi:battery-alert-variant-outline
    {% endif %}
  icon_color: |-
    {% set battery_level = states( '[[entity]]' ) | int %}
    {% if battery_level > 90 %}
      green
    {% elif battery_level > 60 %}
      light-green
    {% elif battery_level > 50 %}
      lime
    {% elif battery_level > 40 %}
      yellow
    {% elif battery_level > 30 %}
      amber
    {% elif battery_level > 20 %}
      orange
    {% elif battery_level > 10 %}
      deep-orange
    {% else %}
      red
    {% endif %}
