################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Media Player
# @description :
#
################################################################################

default:
  - device: "tv"
card:
  type: custom:mushroom-media-player-card
  entity: '[[entity]]'
  collapsible_controls: true
  use_media_info: true
  media_controls: >-
    {% if device == 'appletv' %}
      [on_off, play_pause_stop]
    {% elif device == 'alexa' %}
      [on_off, previous, play_pause_stop, next]
    {% else %}
      [on_off]
    {% endif %}
  show_volume_level: true
  volume_controls: >-
    {% if device == 'appletv' %}
      []
    {% elif device == 'alexa' %}
      []
    {% else %}
      [volume_mute, volume_set, volume_buttons]
    {% endif %}