################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Door Details
# @description :
#
################################################################################

default:
  - icon_open: "door-open"
  - icon_closed: "door-closed"
  - icon_unknown: "alert-circle-outline"
  - show_battery: "true"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  secondary: >-
    {% if not is_state( '[[battery]]', 'unavailable' ) %}
      {% set state_battery = states( '[[battery]]' ) | lower %}
      Battery: {{ state_battery }}%
    {% else %}
      {% set state_entity = states( '[[entity]]' ) | lower %}
      {% if state_entity == 'on' %}
        Open
      {% elif state_entity == 'off' %}
        Closed
      {% else %}
        Unknown
      {% endif %}
    {% endif %}
  icon: >-
    {% set state_entity = states( '[[entity]]' ) | lower %}
    {% if state_entity == 'on' %}
      mdi:[[icon_open]]
    {% elif state_entity == 'off' %}
      mdi:[[icon_closed]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}
  icon_color: >-
    {% set show_battery = '[[show_battery]]' %}
    {% set state_entity = states( '[[entity]]' ) %}

    {% if show_battery == 'true' %}
      {% set state_battery = states( '[[battery]]' ) | int %}

      {% if state_battery > 50 %}
        {%if state_entity == 'on' %}
          green
        {% else %}
          disabled
        {% endif %}
      {% elif state_battery > 40 %}
        yellow
      {% elif state_battery > 30 %}
        amber
      {% elif state_battery > 20 %}
        orange
      {% elif state_battery > 10 %}
        deep-orange
      {% else %}
        red
      {% endif %}
    {% else %}
      {% if state_entity == 'on' %}
        green
      {% else %}
        disabled
      {% endif %}
    {% endif %}
  # icon_color: >-
  #   {% set state_entity = states( '[[entity]]' ) %}
  #   {% if state_entity == 'on' %}
  #     green
  #   {% elif state_entity == 'off' %}
  #     disabled
  #   {% else %}
  #     disabled
  #   {% endif %}
