################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Media Player (AppleTV)
# @description :
#
################################################################################

card:
  type: custom:mushroom-media-player-card
  entity: "[[entity]]"
  name: "[[name]]"
  #primary_info: Tacos
  #secondary_info: Cheese
  collapsible_controls: true
  use_media_info: false
  media_controls:
    - on_off
    - play_pause_stop
  show_volume_level: false
