################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Door Details
# @description :
#
################################################################################

default:
  - icon_open: "door-open"
  - icon_closed: "door-closed"
  - icon_unknown: "alert-circle-outline"
  - show_battery: "true"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  secondary: >-
    {% set ignore = [ 'none', 'unknown', 'unavilable' ] %}
    {% set state = states( '[[entity]]' ) | lower %}
    {% set battery_level = state_attr( '[[entity]]', 'battery' ) %}
    {% if state not in ignore and battery_level not in ignore %}
      Battery: {{ battery_level }}%
    {% else %}
      {% if state == 'on' %}
        Open
      {% elif state == 'off' %}
        Closed
      {% else %}
        Unknown
      {% endif %}
    {% endif %}
  icon: >-
    {% set state = states( '[[entity]]' ) | lower %}
    {% if state == 'on' %}
      mdi:[[icon_open]]
    {% elif state == 'off' %}
      mdi:[[icon_closed]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}
  icon_color: >-
    {% set show_battery = '[[show_battery]]' %}
    {% set state = states( '[[entity]]' ) %}

    {% if show_battery == 'true' %}
      {% set battery_level = state_attr( '[[entity]]', 'battery' ) | int %}

      {% if battery_level > 50 %}
        {%if state == 'on' %}
          green
        {% else %}
          disabled
        {% endif %}
      {% elif battery_level > 40 %}
        yellow
      {% elif battery_level > 30 %}
        amber
      {% elif battery_level > 20 %}
        orange
      {% elif battery_level > 10 %}
        deep-orange
      {% else %}
        red
      {% endif %}
    {% else %}
      {% if state == 'on' %}
        green
      {% else %}
        disabled
      {% endif %}
    {% endif %}
  # icon_color: >-
  #   {% set state = states( '[[entity]]' ) %}
  #   {% if state == 'on' %}
  #     green
  #   {% elif state == 'off' %}
  #     disabled
  #   {% else %}
  #     disabled
  #   {% endif %}
