################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Leak Details
# @description :
#
################################################################################

default:
  - icon_on: "water"
  - icon_off: "water-off"
  - icon_unknown: "alert-circle-outline"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  secondary: >-
    {% set ignore = [ 'none', 'unknown', 'unavilable' ] %}
    {% set state = states( '[[entity]]' ) | lower %}
    {% set battery_level = state_attr( '[[entity]]', 'battery' ) %}
    {% if state not in ignore and battery_level not in ignore %}
      Battery: {{ battery_level }}%
    {% else %}
      {% if state == 'on' %}
        Wet
      {% elif state == 'off' %}
        Dry
      {% else %}
        Unknown
      {% endif %}
    {% endif %}

  icon: >-
    {% set state = states( '[[entity]]' ) | lower %}
    {% if state == 'on' %}
      mdi:[[icon_on]]
    {% elif state == 'off' %}
      mdi:[[icon_off]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}

  icon_color: >-
    {% set state = states( '[[entity]]' ) | lower %}
    {% if state == 'on' %}
      red
    {% elif state == 'off' %}
      disabled
    {% else %}
      disabled
    {% endif %}
