################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Battery Level
# @description :
#
################################################################################

card:
  type: custom:mushroom-template-card
  entity: "[[entity]]"
  primary: "[[name]]"
  secondary: >-
    {% set ignore = [ 'none', 'unknown', 'unavilable' ] %}
    {% set battery_level = states( '[[entity]]' ) | lower %}
    {% if battery_level not in ignore %}
      Battery: {{ battery_level }}%
    {% else %}
      Unknown
    {% endif %}
  icon: >-
    {% set battery_level = ( states( '[[entity]]' ) | int / 10 ) | round(0) | int * 10 %}
    {% if battery_level == 100 %}
      mdi:battery
    {% elif battery_level > 20 %}
      mdi:battery-{{ battery_level }}
    {% else %}
      mdi:battery-alert-variant-outline
    {% endif %}
  icon_color: >-
    {% set battery_level = states( '[[entity]]' ) | int %}
    {% if battery_level > 90 %}
      green
    {% elif battery_level > 75 %}
      light-green
    {% elif battery_level > 60 %}
      lime
    {% elif battery_level > 50 %}
      yellow
    {% elif battery_level > 40 %}
      orange
    {% elif battery_level > 30 %}
      deep-orange
    {% else %}
      red
    {% endif %}
