################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Leak Details
# @description :
#
################################################################################

default:
  - icon_on: "water"
  - icon_off: "water-off"
  - icon_unknown: "alert-circle-outline"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  secondary: "Battery: {{ state_attr( '[[entity]]', 'battery' ) }}%"
  icon: |-
    {% set state = states( '[[entity]]' ) %}
    {% if state == 'on' %}
      mdi:[[icon_on]]
    {% elif state == 'off' %}
      mdi:[[icon_off]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}
  icon_color: |-
    {% set state = states( '[[entity]]' ) %}
    {% if state == 'on' %}
      red
    {% elif state == 'off' %}
      disabled
    {% else %}
      disabled
    {% endif %}
