################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Leak Details
# @description :
#
################################################################################

default:
  - icon_on: "water"
  - icon_off: "water-off"
  - icon_unknown: "alert-circle-outline"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  secondary: >-
    {% set ignore = [ 'none', 'unknown', 'unavilable' ] %}
    {% set state_entity = states( '[[entity]]' ) | lower %}
    {% set state_battery = states( '[[battery]]' ) %}
    {% if state_entity not in ignore and state_battery not in ignore %}
      Battery: {{ state_battery }}%
    {% else %}
      {% if state_entity == 'on' %}
        Wet
      {% elif state_entity == 'off' %}
        Dry
      {% else %}
        Unknown
      {% endif %}
    {% endif %}

  icon: >-
    {% set state_entity = states( '[[entity]]' ) | lower %}
    {% if state_entity == 'on' %}
      mdi:[[icon_on]]
    {% elif state_entity == 'off' %}
      mdi:[[icon_off]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}

  icon_color: >-
    {% set state_entity = states( '[[entity]]' ) | lower %}
    {% if state_entity == 'on' %}
      red
    {% elif state_entity == 'off' %}
      disabled
    {% else %}
      disabled
    {% endif %}
