################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Media Player (Alexa)
# @description :
#
################################################################################

card:
  type: custom:mushroom-media-player-card
  entity: '[[entity]]'
  collapsible_controls: true
  use_media_info: true
  media_controls: [on_off, previous, play_pause_stop, next]
  show_volume_level: true
  volume_controls: [volume_mute, volume_set, volume_buttons]
