################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Power Outlet
# @description :
#
################################################################################

default:
  - icon_on: "power-plug"
  - icon_off: "power-plug-off"
  - icon_unknown: "alert-circle-outline"
card:
  type: custom:mushroom-template-card
  primary: "[[name]]"
  icon: |-
    {% set state = states( '[[entity]]' ) %}
    {% if state == 'on' %}
      mdi:[[icon_on]]
    {% elif state == 'off' %}
      mdi:[[icon_off]]
    {% else %}
      mdi:[[icon_unknown]]
    {% endif %}
  icon_color: |-
    {% set state = states( '[[entity]]' ) %}
    {% if state == 'on' %}
      green
    {% elif state == 'off' %}
      disabled
    {% else %}
      disabled
    {% endif %}
