################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Battery Level
# @description :
#
################################################################################

card:
  type: custom:mushroom-template-card
  entity: "[[entity]]"
  primary: "[[name]]"
  secondary: >-
    {% if not is_state( '[[battery]]', 'unavailable' ) %}
      {% set state_battery = states( '[[battery]]' ) | lower %}
      Battery: {{ state_battery }}%
    {% else %}
      Unknown
    {% endif %}
  icon: >-
    {% set state_battery = ( states( '[[battery]]' ) | int / 10 ) | round(0) | int * 10 %}
    {% if state_battery == 100 %}
      mdi:battery
    {% elif state_battery > 20 %}
      mdi:battery-{{ state_battery }}
    {% else %}
      mdi:battery-alert-variant-outline
    {% endif %}
  icon_color: >-
    {% set state_battery = states( '[[battery]]' ) | int %}
    {% if state_battery > 90 %}
      green
    {% elif state_battery > 75 %}
      light-green
    {% elif state_battery > 60 %}
      lime
    {% elif state_battery > 50 %}
      yellow
    {% elif state_battery > 40 %}
      orange
    {% elif state_battery > 30 %}
      deep-orange
    {% else %}
      red
    {% endif %}
