################################################################################
#
# @author      : Thomas Maxson
# @package     : Entity, Media Player (AppleTV)
# @description :
#
################################################################################

card:
  type: custom:mushroom-media-player-card
  entity: '[[entity]]'
  collapsible_controls: true
  use_media_info: true
  media_controls: [on_off, play_pause_stop]
  show_volume_level: false
