################################################################################
#
# @author      : Thomas Maxson
# @package     : Person Details
# @description :
#
################################################################################

default:
  - notify_general: "false"
  - notify_info: "false"
  - notify_warning: "false"
  - notify_critical: "false"
  - notify_activity: "false"
  - notify_activity_door_interior: "false"
  - notify_activity_door_exterior: "false"
  - notify_activity_person_locations: "false"
card:
  type: entities
  show_header_toggle: false
  card_mod:
    class: header
    style: |
      ha-card {
        margin: 0 !important;
        width: 100%;
      }

      .name { margin: 0 0 1em !important;}

      #states > div:nth-child(5), 
      #states > div:nth-child(6), 
      #states > div:nth-child(7) { padding-left: 45px !important;}
  entities:
    - type: section

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_info]]"
        name: Recieve Notifications

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_info]]"
        name: Informational Notifications

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_activity]]"
        name: Activity Notifications

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
        - entity: "[[notify_activity]]"
          state: "on"
        - entity: "[[notify_activity]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_activity_door_exterior]]"
        name: Doors (Exterior)

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
        - entity: "[[notify_activity]]"
          state: "on"
        - entity: "[[notify_activity]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_activity_door_interior]]"
        name: Doors (Interior)

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
        - entity: "[[notify_activity]]"
          state: "on"
        - entity: "[[notify_activity]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_activity_person_locations]]"
        name: Person Location

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_warning]]"
        name: Warning Notifications

    - type: conditional
      conditions:
        - entity: "[[notify_general]]"
          state: "on"
        - entity: "[[notify_general]]"
          state_not: "unavailable"
      row:
        entity: "[[notify_critical]]"
        name: Critical Notifications
